In [1]:
!conda env list

# conda environments:
#
base                  *  /opt/conda
federated_learning       /opt/conda/envs/federated_learning
python2                  /opt/conda/envs/python2
pytorch1.8               /opt/conda/envs/pytorch1.8
rapids                   /opt/conda/envs/rapids
tf1.14                   /opt/conda/envs/tf1.14
tf2.4.1                  /opt/conda/envs/tf2.4.1



In [2]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForMaskedLM, AutoModelForSequenceClassification
from tqdm import tqdm
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, classification_report
import wandb

/root/.local/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2022-05-08 00:30:18.526064: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64
2022-05-08 00:30:18.526437: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64
2022-05-08 00:30:18.526453: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing l

In [3]:
!nvidia-smi
wandb.init(project="senti-analysis", entity='cocoshe', mode='disabled')
# wandb.config = {
#     'batch_size': 32,
#     'epochs': 5,
#     'lr': 5e-5,
#     'max_seq_length': 128,
# }
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

Sun May  8 00:30:24 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:3E:00.0 Off |                    0 |
| N/A   35C    P0    39W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.


In [4]:
class MyDataset(Dataset):
    def __init__(self, df, model_name='bert-base-chinese'):
        self.data_df = df
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)

    def __len__(self):
        return len(self.data_df)

    def __getitem__(self, idx):
        input_text = self.data_df.iloc[idx, 0]
        label = self.data_df.iloc[idx, 1]

        tokenizer = self.tokenizer
        token = tokenizer(input_text, padding='max_length', truncation=True, max_length=128, return_tensors='pt', return_token_type_ids=False)
        input_ids = token['input_ids'].squeeze(0)
        attention_mask = token['attention_mask'].squeeze(0)
        label = np.int64(label)
        return input_ids.to(device), attention_mask.to(device), label

In [5]:
tokenizer = AutoTokenizer.from_pretrained('hfl/chinese-roberta-wwm-ext')
model = AutoModelForSequenceClassification.from_pretrained('hfl/chinese-roberta-wwm-ext', num_labels=5)
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
epochs = 20

Some weights of the model checkpoint at hfl/chinese-roberta-wwm-ext were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model che

In [6]:
def train_test_split(input_df, test_size=0.2, shuffle=True, random_state=None):
    if shuffle:
        input_df = input_df.sample(frac=1)
    ret_train_df = input_df[:int(len(input_df) * (1 - test_size))]
    ret_test_df = input_df[int(len(input_df) * (1 - test_size)):]
    return ret_train_df, ret_test_df


In [7]:
evaluate2score = {'力荐': '4', '推荐': '3', '还行': '2', '较差': '1', '很差': '0'}
score2evaluate = {4: '力荐', '3': '推荐', '2': '还行', '1': '较差', '0': '很差'}
evaluate_list = ['力荐', '推荐', '还行', '较差', '很差']
k, v = list(evaluate2score.items())[0]

In [8]:
# split train and test data directly(no need to split input and label, that's why not use sklearn.model_selection.train_test_split)
df = pd.read_csv('dataset/流浪地球.csv', encoding='utf-8', header=0, index_col=None, usecols=['content', 'evaluate'])
print(df.drop_duplicates(['evaluate'])['evaluate'])
df = df[df['evaluate'].isin(evaluate_list)]  # filter out the evaluate not in evaluate_list
print('after filter')
print(df.drop_duplicates(['evaluate'])['evaluate'])
df.head()

0                       推荐
2                       很差
3                       力荐
5                       还行
6                       较差
56     2019-02-05 23:16:40
96     2019-02-08 11:53:57
119    2019-02-09 09:14:52
161    2019-01-28 20:14:00
247    2019-02-10 23:30:50
261    2019-02-06 20:33:03
307    2019-02-06 15:31:25
339    2019-02-10 18:09:43
354    2019-02-08 05:09:17
395    2019-02-08 00:15:25
417    2019-02-09 18:32:26
431    2019-02-08 22:39:41
446    2019-02-07 19:41:14
463    2019-02-08 22:00:00
Name: evaluate, dtype: object
after filter
0    推荐
2    很差
3    力荐
5    还行
6    较差
Name: evaluate, dtype: object


content evaluate
0            一个悲伤的故事：太阳都要毁灭，地球都要流浪了，我国的校服还是这么丑......       推荐
1  电影比预期要更恢弘磅礴，晨昏线过后的永夜、火种计划、让地球流浪、木星推动地球…等等大小设定，...       推荐
2  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...       很差
3  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...       力荐
4  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...       很差

In [9]:
df['evaluate'] = df['evaluate'].map(evaluate2score).astype(int)
print(df.dtypes)
df.head()


content     object
evaluate     int64
dtype: object


content  evaluate
0            一个悲伤的故事：太阳都要毁灭，地球都要流浪了，我国的校服还是这么丑......         3
1  电影比预期要更恢弘磅礴，晨昏线过后的永夜、火种计划、让地球流浪、木星推动地球…等等大小设定，...         3
2  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...         0
3  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...         4
4  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...         0

In [10]:
train_df, test_df = train_test_split(df, test_size=0.3, shuffle=True)

train_dataset = MyDataset(train_df, model_name='hfl/chinese-roberta-wwm-ext')
test_dataset = MyDataset(test_df, model_name='hfl/chinese-roberta-wwm-ext')

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)


In [11]:
# train
def train():
    model.train()
    for epoch in range(epochs):
        for i, batch in enumerate(tqdm(train_loader)):
            input_ids, attention_mask, label = batch
            input_ids, attention_mask, label = input_ids.to(device), attention_mask.to(device), label.to(device)
            print(label)
            output = model(input_ids, attention_mask, labels=label)
            loss = output[0]

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            print('epoch: ', epoch, 'loss: ', loss.item())
            wandb.log({'epoch': epoch,'step': i, 'loss': loss.item()})

        evaluate()

In [12]:
# evaluate
def evaluate():
    label_list = []
    pred_list = []
    model.eval()
    with torch.no_grad():
        model.eval()
        eval_steps = 0
        pred_list = []
        label_list = []
        for i, batch in enumerate(tqdm(test_loader)):
            input_ids, attention_mask, label = batch
            input_ids, attention_mask, label = input_ids.to(device), attention_mask.to(device), label.to(device)
            output = model(input_ids, attention_mask, labels=label)
            pred_list += (torch.argmax(output[1], dim=-1))
            label_list += label
            eval_steps += 1

        label_list, pred_list = [item.cpu().numpy() for item in label_list], [item.cpu().numpy() for item in pred_list]
        # f1 = f1_score(label_list, pred_list, average='macro')
        # acc = accuracy_score(label_list, pred_list)
        # precision = precision_score(label_list, pred_list, average='macro')
        # recall = recall_score(label_list, pred_list, average='macro')
        report = classification_report(label_list, pred_list)
        print(report)

In [ ]:
train()
# evaluate()
# torch.save(model.state_dict(), 'model/bert_cls_model.pth')

  0%|          | 0/11 [00:00<?, ?it/s]

tensor([4, 0, 0, 3, 1, 4, 2, 3, 4, 0, 2, 4, 4, 0, 1, 4, 0, 3, 4, 2, 1, 3, 4, 1,
        2, 3, 1, 3, 4, 2, 4, 2], device='cuda:0')


  9%|▉         | 1/11 [00:01<00:12,  1.23s/it]

epoch:  0 loss:  1.6250149011611938
tensor([2, 3, 2, 2, 3, 1, 2, 4, 4, 2, 2, 2, 1, 2, 4, 3, 3, 1, 3, 4, 3, 2, 2, 2,
        1, 2, 4, 2, 1, 1, 3, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:07,  1.28it/s]

epoch:  0 loss:  1.5724525451660156
tensor([2, 2, 0, 2, 4, 3, 2, 3, 1, 2, 2, 4, 0, 0, 4, 0, 4, 3, 1, 2, 2, 1, 4, 3,
        3, 0, 3, 3, 2, 4, 2, 0], device='cuda:0')


 27%|██▋       | 3/11 [00:01<00:04,  1.82it/s]

epoch:  0 loss:  1.638895034790039
tensor([3, 2, 4, 0, 4, 4, 1, 3, 4, 0, 1, 3, 3, 2, 1, 4, 3, 1, 1, 0, 0, 3, 4, 4,
        3, 1, 2, 0, 3, 4, 2, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:03,  2.25it/s]

epoch:  0 loss:  1.618898868560791
tensor([2, 3, 3, 2, 1, 0, 4, 3, 4, 1, 3, 2, 0, 0, 3, 1, 2, 2, 1, 2, 0, 3, 3, 2,
        2, 4, 2, 4, 3, 4, 4, 0], device='cuda:0')


 45%|████▌     | 5/11 [00:02<00:02,  2.58it/s]

epoch:  0 loss:  1.6599855422973633
tensor([1, 1, 4, 3, 3, 2, 1, 2, 4, 3, 1, 2, 2, 3, 4, 3, 3, 2, 3, 4, 4, 0, 2, 1,
        1, 1, 4, 4, 2, 3, 2, 2], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.02it/s]

epoch:  0 loss:  1.5252153873443604
tensor([4, 4, 3, 2, 3, 2, 1, 2, 3, 3, 1, 0, 1, 0, 4, 1, 1, 1, 3, 3, 1, 3, 0, 0,
        3, 3, 3, 4, 2, 3, 4, 3], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.01it/s]

epoch:  0 loss:  1.5701954364776611
tensor([3, 0, 1, 0, 2, 3, 1, 0, 2, 3, 2, 3, 1, 2, 2, 4, 2, 2, 4, 3, 3, 0, 3, 0,
        4, 1, 1, 3, 4, 4, 0, 1], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.09it/s]

epoch:  0 loss:  1.5758212804794312
tensor([4, 3, 2, 4, 1, 1, 2, 3, 3, 3, 3, 2, 3, 3, 2, 4, 2, 3, 4, 1, 2, 0, 1, 2,
        1, 3, 1, 2, 2, 3, 1, 4], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.15it/s]

epoch:  0 loss:  1.4865658283233643
tensor([2, 1, 2, 2, 3, 3, 3, 4, 3, 2, 1, 3, 0, 2, 4, 2, 3, 0, 0, 3, 2, 4, 3, 4,
        3, 3, 4, 2, 1, 2, 4, 4], device='cuda:0')


 91%|█████████ | 10/11 [00:08<00:00,  1.15it/s]

epoch:  0 loss:  1.4972474575042725
tensor([3, 2, 1, 2, 3, 4], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.30it/s]


epoch:  0 loss:  1.5111454725265503


100%|██████████| 5/5 [00:01<00:00,  3.94it/s]
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.00      0.00      0.00        23
           2       0.00      0.00      0.00        35
           3       0.23      1.00      0.37        32
           4       0.00      0.00      0.00        35

    accuracy                           0.23       140
   macro avg       0.05      0.20      0.07       140
weighted avg       0.05      0.23      0.09       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([1, 2, 2, 3, 4, 1, 1, 1, 3, 0, 2, 0, 2, 3, 0, 4, 1, 2, 4, 2, 3, 4, 2, 1,
        2, 2, 0, 1, 4, 3, 3, 2], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.74it/s]

epoch:  1 loss:  1.5418375730514526
tensor([2, 4, 3, 4, 2, 2, 1, 3, 0, 3, 3, 3, 3, 3, 2, 2, 3, 3, 3, 1, 3, 3, 1, 3,
        1, 2, 2, 2, 3, 3, 4, 1], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.63it/s]

epoch:  1 loss:  1.2541155815124512
tensor([2, 1, 0, 4, 1, 0, 4, 2, 0, 1, 0, 1, 3, 4, 3, 1, 0, 1, 3, 1, 0, 3, 0, 4,
        1, 2, 3, 4, 0, 2, 3, 1], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.37it/s]

epoch:  1 loss:  1.5355048179626465
tensor([2, 1, 4, 2, 2, 2, 4, 2, 3, 3, 0, 4, 3, 2, 3, 1, 2, 1, 4, 0, 2, 2, 4, 4,
        2, 1, 4, 0, 2, 3, 1, 4], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.26it/s]

epoch:  1 loss:  1.3967156410217285
tensor([1, 3, 3, 1, 3, 3, 4, 1, 3, 3, 3, 1, 2, 2, 2, 1, 0, 4, 2, 3, 2, 0, 2, 3,
        0, 2, 0, 1, 3, 1, 2, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.28it/s]

epoch:  1 loss:  1.246167540550232
tensor([2, 4, 2, 3, 0, 4, 2, 4, 3, 3, 1, 3, 2, 4, 4, 2, 1, 1, 0, 4, 0, 3, 4, 2,
        2, 2, 3, 3, 3, 0, 2, 4], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.28it/s]

epoch:  1 loss:  1.449560523033142
tensor([2, 1, 0, 4, 0, 2, 2, 3, 2, 3, 4, 0, 0, 2, 1, 1, 3, 3, 4, 4, 4, 1, 3, 2,
        3, 2, 4, 3, 4, 2, 3, 1], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.24it/s]

epoch:  1 loss:  1.298372745513916
tensor([3, 1, 0, 3, 4, 3, 4, 3, 4, 3, 1, 3, 4, 0, 3, 4, 3, 2, 1, 3, 4, 4, 1, 4,
        3, 1, 2, 0, 2, 2, 3, 3], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.27it/s]

epoch:  1 loss:  1.3348865509033203
tensor([2, 2, 3, 3, 2, 4, 3, 2, 2, 3, 4, 3, 2, 3, 1, 3, 2, 4, 1, 4, 1, 4, 3, 3,
        4, 2, 1, 2, 2, 2, 2, 4], device='cuda:0')


 82%|████████▏ | 9/11 [00:06<00:01,  1.28it/s]

epoch:  1 loss:  1.123318076133728
tensor([4, 1, 4, 2, 3, 3, 2, 4, 4, 1, 2, 4, 2, 0, 4, 4, 0, 4, 1, 4, 1, 2, 3, 4,
        3, 0, 4, 0, 2, 3, 4, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.23it/s]

epoch:  1 loss:  1.2012994289398193
tensor([3, 1, 2, 3, 0, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.35it/s]


epoch:  1 loss:  1.2662519216537476


100%|██████████| 5/5 [00:01<00:00,  3.92it/s]
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.29      0.09      0.13        23
           2       0.27      0.43      0.33        35
           3       0.29      0.16      0.20        32
           4       0.39      0.69      0.50        35

    accuracy                           0.33       140
   macro avg       0.25      0.27      0.23       140
weighted avg       0.28      0.33      0.28       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([1, 3, 2, 0, 4, 1, 4, 3, 2, 3, 4, 4, 3, 1, 4, 2, 3, 4, 0, 0, 1, 2, 3, 2,
        3, 2, 0, 4, 3, 3, 3, 4], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.72it/s]

epoch:  2 loss:  1.010979175567627
tensor([0, 2, 3, 3, 4, 4, 1, 2, 3, 2, 4, 1, 4, 2, 2, 3, 2, 2, 2, 3, 2, 0, 1, 4,
        1, 4, 1, 0, 2, 3, 0, 0], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:06,  1.48it/s]

epoch:  2 loss:  1.029964804649353
tensor([3, 0, 1, 0, 0, 1, 0, 2, 2, 4, 1, 2, 0, 1, 3, 3, 3, 2, 2, 4, 3, 3, 2, 0,
        1, 2, 2, 4, 0, 1, 2, 1], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:06,  1.32it/s]

epoch:  2 loss:  1.06698739528656
tensor([4, 1, 3, 1, 3, 4, 3, 2, 3, 4, 1, 2, 3, 2, 4, 3, 2, 1, 2, 3, 2, 2, 3, 2,
        2, 4, 2, 2, 0, 4, 1, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:03<00:05,  1.24it/s]

epoch:  2 loss:  1.0530134439468384
tensor([3, 2, 4, 1, 0, 2, 4, 4, 3, 1, 0, 2, 3, 3, 2, 4, 1, 3, 4, 1, 4, 4, 4, 0,
        0, 1, 3, 4, 2, 1, 3, 1], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.26it/s]

epoch:  2 loss:  0.9793497920036316
tensor([1, 3, 3, 2, 4, 1, 2, 3, 3, 3, 3, 4, 1, 2, 2, 2, 1, 4, 3, 4, 3, 4, 4, 1,
        2, 2, 1, 3, 2, 4, 4, 2], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.29it/s]

epoch:  2 loss:  0.8412622213363647
tensor([2, 3, 2, 4, 1, 1, 4, 3, 4, 3, 3, 2, 0, 4, 1, 2, 2, 2, 3, 3, 4, 4, 2, 2,
        4, 3, 4, 4, 0, 3, 3, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.24it/s]

epoch:  2 loss:  0.7685455679893494
tensor([4, 3, 0, 3, 4, 2, 1, 0, 2, 1, 3, 3, 3, 1, 0, 2, 3, 2, 2, 4, 3, 2, 1, 2,
        4, 3, 1, 4, 3, 3, 3, 3], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.26it/s]

epoch:  2 loss:  0.8005179166793823
tensor([4, 3, 4, 0, 1, 4, 2, 3, 1, 1, 1, 3, 0, 2, 3, 3, 3, 2, 2, 4, 1, 2, 3, 3,
        2, 3, 0, 4, 1, 3, 2, 4], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.23it/s]

epoch:  2 loss:  0.911045253276825
tensor([2, 1, 3, 0, 3, 1, 4, 0, 2, 3, 1, 3, 2, 4, 0, 3, 2, 2, 2, 3, 2, 1, 1, 2,
        3, 3, 0, 4, 1, 4, 0, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.26it/s]

epoch:  2 loss:  0.9559375047683716
tensor([0, 0, 3, 2, 2, 1], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.34it/s]


epoch:  2 loss:  0.7509174942970276


100%|██████████| 5/5 [00:01<00:00,  3.69it/s]


              precision    recall  f1-score   support

           0       1.00      0.20      0.33        15
           1       0.20      0.22      0.21        23
           2       0.29      0.46      0.35        35
           3       0.44      0.53      0.48        32
           4       0.59      0.29      0.38        35

    accuracy                           0.36       140
   macro avg       0.50      0.34      0.35       140
weighted avg       0.46      0.36      0.36       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([3, 0, 2, 0, 4, 2, 1, 1, 2, 4, 1, 4, 3, 2, 3, 1, 4, 3, 1, 3, 2, 1, 2, 2,
        3, 2, 0, 3, 3, 1, 1, 3], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.66it/s]

epoch:  3 loss:  0.6214391589164734
tensor([2, 4, 2, 3, 1, 0, 1, 2, 4, 3, 4, 3, 3, 1, 3, 3, 4, 1, 1, 4, 0, 4, 3, 2,
        0, 2, 4, 1, 4, 3, 2, 1], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.61it/s]

epoch:  3 loss:  0.6088160276412964
tensor([4, 1, 4, 0, 1, 3, 2, 2, 3, 1, 0, 2, 0, 3, 4, 3, 1, 2, 3, 2, 0, 3, 2, 0,
        2, 3, 2, 1, 3, 2, 0, 2], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.36it/s]

epoch:  3 loss:  0.7004678845405579
tensor([4, 2, 3, 1, 2, 1, 4, 3, 1, 4, 3, 4, 2, 2, 2, 4, 1, 4, 4, 3, 3, 3, 3, 3,
        0, 3, 2, 4, 2, 4, 2, 4], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.27it/s]

epoch:  3 loss:  0.5167711973190308
tensor([3, 2, 2, 0, 4, 2, 2, 3, 0, 4, 4, 4, 4, 2, 0, 4, 4, 0, 2, 3, 3, 3, 3, 1,
        0, 3, 1, 0, 4, 4, 3, 3], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.29it/s]

epoch:  3 loss:  0.45053499937057495
tensor([1, 2, 2, 1, 4, 3, 0, 4, 4, 1, 2, 2, 3, 3, 2, 2, 2, 3, 3, 4, 4, 3, 0, 2,
        2, 3, 0, 0, 0, 4, 4, 2], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.29it/s]

epoch:  3 loss:  0.46189481019973755
tensor([2, 1, 3, 4, 2, 2, 3, 4, 2, 4, 4, 2, 4, 4, 0, 3, 1, 4, 3, 2, 3, 3, 2, 2,
        2, 3, 1, 0, 1, 3, 4, 2], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.30it/s]

epoch:  3 loss:  0.4377031922340393
tensor([2, 4, 1, 2, 1, 1, 3, 3, 3, 4, 0, 3, 2, 4, 0, 1, 2, 1, 2, 2, 2, 2, 4, 1,
        3, 1, 3, 2, 2, 3, 3, 4], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.24it/s]

epoch:  3 loss:  0.45351696014404297
tensor([2, 3, 2, 2, 3, 2, 4, 1, 3, 2, 1, 3, 2, 1, 0, 1, 4, 0, 2, 3, 0, 3, 3, 3,
        4, 2, 4, 3, 3, 1, 1, 3], device='cuda:0')


 82%|████████▏ | 9/11 [00:06<00:01,  1.27it/s]

epoch:  3 loss:  0.44869109988212585
tensor([2, 1, 4, 2, 3, 4, 4, 3, 4, 1, 1, 0, 3, 4, 0, 1, 1, 2, 3, 2, 1, 1, 4, 0,
        0, 3, 2, 3, 2, 1, 4, 3], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.23it/s]

epoch:  3 loss:  0.4393433630466461
tensor([1, 2, 3, 3, 0, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.35it/s]


epoch:  3 loss:  0.2874082326889038


100%|██████████| 5/5 [00:01<00:00,  3.68it/s]


              precision    recall  f1-score   support

           0       1.00      0.20      0.33        15
           1       0.24      0.17      0.20        23
           2       0.29      0.43      0.35        35
           3       0.38      0.56      0.45        32
           4       0.67      0.40      0.50        35

    accuracy                           0.39       140
   macro avg       0.51      0.35      0.37       140
weighted avg       0.47      0.39      0.38       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([3, 0, 0, 4, 4, 3, 2, 3, 3, 0, 2, 3, 4, 1, 0, 4, 1, 0, 2, 3, 3, 3, 2, 1,
        1, 0, 2, 2, 3, 1, 2, 1], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.63it/s]

epoch:  4 loss:  0.29607027769088745
tensor([3, 3, 2, 2, 0, 3, 0, 2, 1, 0, 1, 1, 4, 2, 4, 1, 3, 2, 3, 3, 3, 2, 4, 2,
        4, 0, 3, 4, 4, 3, 2, 3], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.59it/s]

epoch:  4 loss:  0.2401265799999237
tensor([1, 2, 1, 4, 4, 3, 3, 3, 1, 3, 1, 3, 2, 4, 3, 2, 4, 2, 2, 3, 1, 1, 3, 1,
        1, 1, 3, 4, 2, 2, 3, 2], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.36it/s]

epoch:  4 loss:  0.19556696712970734
tensor([4, 3, 2, 2, 4, 4, 0, 2, 3, 2, 3, 4, 1, 2, 3, 3, 2, 0, 2, 4, 1, 3, 2, 3,
        3, 3, 3, 0, 3, 4, 1, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.27it/s]

epoch:  4 loss:  0.17286179959774017
tensor([4, 3, 2, 2, 2, 1, 3, 0, 2, 2, 3, 2, 1, 2, 3, 3, 1, 3, 0, 2, 1, 1, 2, 4,
        0, 3, 1, 2, 1, 1, 0, 1], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.28it/s]

epoch:  4 loss:  0.22153812646865845
tensor([3, 4, 2, 0, 4, 2, 1, 4, 0, 3, 4, 2, 4, 1, 3, 3, 3, 2, 2, 4, 1, 2, 2, 1,
        4, 0, 4, 2, 4, 0, 3, 2], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.30it/s]

epoch:  4 loss:  0.21809524297714233
tensor([4, 3, 2, 2, 3, 2, 3, 1, 2, 4, 1, 2, 3, 1, 0, 2, 0, 0, 3, 1, 2, 2, 1, 3,
        1, 1, 1, 4, 4, 3, 1, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.25it/s]

epoch:  4 loss:  0.13648925721645355
tensor([2, 1, 4, 2, 1, 4, 0, 0, 4, 1, 2, 3, 2, 3, 3, 2, 0, 4, 4, 4, 2, 2, 3, 4,
        4, 0, 4, 1, 3, 4, 2, 3], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.22it/s]

epoch:  4 loss:  0.12505464255809784
tensor([2, 4, 3, 2, 0, 2, 2, 3, 4, 2, 4, 3, 4, 1, 2, 1, 3, 3, 2, 0, 3, 2, 4, 4,
        1, 1, 3, 4, 2, 4, 0, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.24it/s]

epoch:  4 loss:  0.1462334245443344
tensor([4, 4, 0, 0, 3, 3, 3, 4, 2, 4, 2, 4, 4, 2, 3, 0, 3, 3, 2, 0, 4, 1, 2, 3,
        4, 4, 3, 1, 3, 0, 4, 3], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.21it/s]

epoch:  4 loss:  0.12334317713975906
tensor([2, 1, 3, 3, 2, 3], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.33it/s]


epoch:  4 loss:  0.08659953624010086


100%|██████████| 5/5 [00:01<00:00,  3.65it/s]


              precision    recall  f1-score   support

           0       0.44      0.27      0.33        15
           1       0.38      0.22      0.28        23
           2       0.34      0.31      0.33        35
           3       0.34      0.72      0.46        32
           4       0.53      0.29      0.37        35

    accuracy                           0.38       140
   macro avg       0.41      0.36      0.35       140
weighted avg       0.41      0.38      0.36       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([3, 4, 0, 1, 1, 0, 3, 4, 3, 2, 2, 3, 3, 4, 1, 2, 1, 3, 2, 1, 1, 1, 4, 3,
        4, 2, 4, 3, 1, 1, 4, 3], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.92it/s]

epoch:  5 loss:  0.10506501793861389
tensor([2, 2, 1, 4, 3, 0, 0, 4, 4, 2, 2, 2, 2, 3, 1, 3, 1, 2, 3, 3, 1, 3, 2, 3,
        2, 1, 0, 4, 0, 3, 2, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.54it/s]

epoch:  5 loss:  0.08362217992544174
tensor([0, 3, 1, 4, 3, 1, 2, 2, 0, 4, 1, 1, 0, 4, 2, 2, 3, 4, 3, 4, 2, 2, 4, 3,
        4, 1, 3, 2, 3, 2, 2, 2], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.41it/s]

epoch:  5 loss:  0.0797804519534111
tensor([3, 2, 3, 3, 1, 3, 4, 2, 3, 1, 2, 4, 4, 1, 3, 0, 2, 3, 3, 3, 1, 2, 2, 0,
        1, 1, 4, 1, 1, 3, 4, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.29it/s]

epoch:  5 loss:  0.061452191323041916
tensor([3, 1, 3, 3, 3, 3, 1, 4, 2, 2, 0, 4, 1, 1, 3, 1, 3, 3, 2, 2, 3, 1, 0, 0,
        2, 2, 1, 1, 4, 2, 2, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.24it/s]

epoch:  5 loss:  0.06960848718881607
tensor([1, 0, 4, 3, 4, 0, 1, 1, 3, 4, 2, 3, 4, 0, 4, 4, 2, 4, 0, 3, 2, 3, 3, 0,
        1, 4, 3, 2, 4, 3, 3, 3], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.26it/s]

epoch:  5 loss:  0.06505687534809113
tensor([3, 0, 2, 4, 0, 1, 0, 2, 4, 4, 3, 2, 4, 2, 2, 3, 3, 3, 2, 3, 4, 3, 2, 2,
        3, 3, 3, 0, 4, 4, 0, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.29it/s]

epoch:  5 loss:  0.06835941970348358
tensor([2, 0, 3, 2, 4, 1, 4, 4, 2, 1, 1, 3, 1, 4, 2, 2, 2, 2, 4, 0, 3, 0, 4, 2,
        3, 4, 3, 3, 3, 3, 0, 4], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.24it/s]

epoch:  5 loss:  0.05784387141466141
tensor([3, 1, 2, 1, 3, 0, 4, 3, 3, 4, 2, 1, 0, 2, 3, 3, 4, 2, 2, 2, 2, 4, 2, 4,
        2, 2, 3, 0, 4, 1, 0, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.21it/s]

epoch:  5 loss:  0.05358033627271652
tensor([3, 1, 3, 2, 4, 4, 4, 4, 3, 2, 4, 2, 0, 3, 2, 2, 2, 2, 1, 0, 3, 4, 0, 1,
        4, 0, 2, 1, 1, 2, 3, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.24it/s]

epoch:  5 loss:  0.05034998804330826
tensor([3, 1, 1, 2, 3, 4], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.35it/s]


epoch:  5 loss:  0.03932081535458565


100%|██████████| 5/5 [00:01<00:00,  3.68it/s]


              precision    recall  f1-score   support

           0       0.46      0.40      0.43        15
           1       0.25      0.22      0.23        23
           2       0.38      0.51      0.44        35
           3       0.47      0.56      0.51        32
           4       0.64      0.40      0.49        35

    accuracy                           0.44       140
   macro avg       0.44      0.42      0.42       140
weighted avg       0.45      0.44      0.43       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([0, 1, 2, 3, 0, 4, 0, 4, 0, 3, 1, 2, 3, 3, 3, 2, 3, 2, 1, 3, 1, 3, 2, 3,
        1, 3, 2, 1, 2, 1, 4, 1], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.69it/s]

epoch:  6 loss:  0.04841122403740883
tensor([4, 2, 1, 2, 3, 2, 2, 4, 4, 1, 4, 3, 4, 3, 1, 1, 0, 2, 2, 2, 0, 4, 2, 1,
        2, 4, 4, 2, 3, 3, 3, 3], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.61it/s]

epoch:  6 loss:  0.036847811192274094
tensor([2, 4, 0, 4, 3, 3, 2, 0, 2, 2, 4, 2, 3, 4, 2, 1, 1, 1, 2, 2, 2, 4, 4, 0,
        2, 3, 0, 4, 4, 4, 1, 4], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.36it/s]

epoch:  6 loss:  0.03778797760605812
tensor([3, 3, 2, 3, 1, 2, 3, 4, 3, 4, 2, 1, 2, 0, 2, 3, 1, 0, 4, 0, 3, 0, 3, 3,
        4, 2, 2, 1, 1, 2, 1, 4], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.27it/s]

epoch:  6 loss:  0.038542650640010834
tensor([3, 2, 2, 2, 1, 1, 2, 3, 4, 3, 3, 3, 3, 1, 4, 3, 0, 0, 4, 0, 1, 1, 4, 3,
        4, 0, 0, 2, 2, 3, 4, 1], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.29it/s]

epoch:  6 loss:  0.03664977103471756
tensor([2, 0, 3, 3, 1, 3, 4, 2, 3, 0, 0, 1, 3, 4, 3, 2, 3, 3, 4, 2, 3, 4, 2, 3,
        4, 4, 4, 2, 3, 2, 4, 4], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.24it/s]

epoch:  6 loss:  0.034304194152355194
tensor([3, 1, 1, 4, 4, 1, 1, 3, 3, 2, 2, 3, 2, 2, 1, 2, 3, 3, 1, 1, 1, 0, 4, 3,
        2, 2, 2, 3, 3, 3, 3, 1], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.26it/s]

epoch:  6 loss:  0.025479065254330635
tensor([1, 2, 2, 3, 2, 4, 4, 2, 2, 4, 3, 3, 4, 4, 3, 1, 3, 2, 4, 3, 3, 2, 2, 3,
        2, 4, 0, 2, 3, 2, 2, 1], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.23it/s]

epoch:  6 loss:  0.022094806656241417
tensor([3, 4, 1, 2, 1, 3, 2, 0, 0, 2, 2, 0, 4, 2, 2, 4, 1, 3, 3, 0, 3, 3, 2, 1,
        0, 3, 2, 4, 2, 3, 4, 4], device='cuda:0')


 82%|████████▏ | 9/11 [00:06<00:01,  1.26it/s]

epoch:  6 loss:  0.02708655223250389
tensor([4, 4, 0, 4, 4, 2, 3, 2, 1, 2, 4, 4, 3, 1, 1, 1, 0, 4, 0, 1, 2, 1, 3, 1,
        0, 4, 3, 3, 2, 1, 0, 0], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.22it/s]

epoch:  6 loss:  0.03388543426990509
tensor([3, 0, 2, 2, 3, 3], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.34it/s]


epoch:  6 loss:  0.018811631947755814


100%|██████████| 5/5 [00:01<00:00,  3.65it/s]


              precision    recall  f1-score   support

           0       0.43      0.40      0.41        15
           1       0.23      0.13      0.17        23
           2       0.35      0.51      0.42        35
           3       0.45      0.56      0.50        32
           4       0.59      0.37      0.46        35

    accuracy                           0.41       140
   macro avg       0.41      0.40      0.39       140
weighted avg       0.42      0.41      0.40       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([0, 1, 0, 2, 2, 4, 3, 3, 2, 2, 3, 1, 4, 4, 3, 3, 4, 1, 0, 2, 3, 4, 2, 2,
        1, 3, 3, 3, 2, 3, 2, 2], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.61it/s]

epoch:  7 loss:  0.021712204441428185
tensor([4, 0, 1, 2, 3, 3, 1, 3, 4, 4, 3, 3, 1, 4, 2, 0, 1, 1, 2, 1, 4, 1, 4, 1,
        3, 0, 4, 3, 2, 0, 1, 3], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.60it/s]

epoch:  7 loss:  0.02715945616364479
tensor([2, 3, 3, 1, 4, 2, 4, 3, 4, 3, 2, 3, 4, 3, 1, 2, 2, 3, 2, 2, 3, 2, 2, 4,
        0, 1, 3, 2, 0, 4, 3, 0], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.36it/s]

epoch:  7 loss:  0.02065804973244667
tensor([4, 4, 2, 3, 1, 2, 2, 2, 2, 2, 2, 2, 4, 3, 3, 2, 0, 4, 1, 3, 2, 1, 2, 3,
        4, 1, 2, 4, 1, 2, 2, 1], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.27it/s]

epoch:  7 loss:  0.01877906732261181
tensor([1, 2, 0, 3, 2, 3, 3, 1, 3, 2, 4, 0, 2, 3, 4, 3, 4, 3, 0, 3, 4, 4, 1, 3,
        3, 2, 4, 2, 1, 0, 2, 3], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.28it/s]

epoch:  7 loss:  0.020336385816335678
tensor([1, 2, 2, 4, 2, 1, 3, 2, 4, 2, 4, 0, 1, 3, 3, 3, 4, 4, 1, 0, 2, 3, 0, 3,
        4, 2, 2, 2, 0, 3, 2, 2], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.29it/s]

epoch:  7 loss:  0.0190835352987051
tensor([1, 4, 0, 3, 3, 2, 1, 1, 0, 2, 4, 3, 3, 4, 3, 4, 2, 3, 2, 2, 1, 1, 3, 2,
        1, 4, 3, 4, 2, 3, 0, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.25it/s]

epoch:  7 loss:  0.019186925143003464
tensor([3, 3, 3, 4, 4, 1, 1, 2, 3, 2, 3, 0, 4, 1, 0, 4, 1, 3, 0, 2, 3, 4, 0, 3,
        4, 2, 1, 3, 3, 0, 4, 2], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.21it/s]

epoch:  7 loss:  0.02238672785460949
tensor([2, 0, 4, 4, 3, 3, 4, 4, 2, 3, 0, 3, 2, 1, 2, 3, 3, 1, 2, 1, 1, 3, 2, 2,
        0, 4, 1, 3, 1, 0, 2, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.24it/s]

epoch:  7 loss:  0.01897462084889412
tensor([4, 1, 2, 2, 3, 1, 4, 4, 3, 4, 4, 4, 2, 1, 0, 1, 3, 2, 3, 0, 1, 2, 1, 4,
        1, 0, 0, 3, 4, 0, 3, 4], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.21it/s]

epoch:  7 loss:  0.021074391901493073
tensor([3, 2, 4, 2, 3, 1], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.33it/s]


epoch:  7 loss:  0.011825093068182468


100%|██████████| 5/5 [00:01<00:00,  3.67it/s]


              precision    recall  f1-score   support

           0       0.40      0.40      0.40        15
           1       0.29      0.22      0.25        23
           2       0.43      0.51      0.47        35
           3       0.43      0.56      0.49        32
           4       0.62      0.43      0.51        35

    accuracy                           0.44       140
   macro avg       0.44      0.42      0.42       140
weighted avg       0.45      0.44      0.44       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([0, 3, 3, 4, 1, 0, 0, 4, 1, 1, 2, 0, 0, 1, 2, 3, 3, 1, 4, 2, 4, 1, 4, 2,
        0, 4, 3, 4, 3, 2, 2, 3], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.67it/s]

epoch:  8 loss:  0.018649227917194366
tensor([0, 3, 2, 3, 0, 1, 0, 2, 1, 2, 2, 3, 2, 2, 1, 1, 4, 4, 4, 1, 2, 2, 3, 3,
        4, 0, 4, 3, 3, 3, 3, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.58it/s]

epoch:  8 loss:  0.015830088406801224
tensor([1, 2, 2, 3, 2, 2, 4, 3, 3, 1, 2, 1, 4, 3, 3, 0, 2, 3, 0, 4, 3, 3, 4, 2,
        3, 3, 2, 0, 3, 3, 4, 0], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.36it/s]

epoch:  8 loss:  0.015261802822351456
tensor([1, 3, 3, 1, 1, 2, 2, 3, 2, 2, 0, 3, 2, 2, 3, 4, 4, 4, 3, 3, 4, 0, 3, 1,
        0, 1, 3, 3, 0, 3, 2, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.33it/s]

epoch:  8 loss:  0.015988176688551903
tensor([3, 3, 1, 1, 1, 2, 3, 2, 1, 2, 3, 2, 2, 1, 2, 1, 4, 0, 4, 4, 1, 2, 3, 4,
        1, 4, 4, 1, 2, 4, 3, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.26it/s]

epoch:  8 loss:  0.014234321191906929
tensor([4, 3, 2, 4, 2, 2, 1, 2, 2, 2, 1, 3, 4, 4, 2, 3, 0, 0, 3, 1, 4, 4, 0, 4,
        0, 3, 2, 2, 4, 2, 2, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.28it/s]

epoch:  8 loss:  0.015298941172659397
tensor([2, 2, 2, 3, 4, 2, 3, 0, 2, 1, 4, 4, 3, 1, 1, 2, 0, 3, 4, 4, 0, 0, 4, 3,
        1, 2, 0, 3, 2, 4, 4, 3], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.23it/s]

epoch:  8 loss:  0.014728372916579247
tensor([2, 1, 2, 1, 2, 4, 4, 0, 3, 2, 0, 4, 2, 1, 2, 3, 2, 4, 4, 4, 3, 2, 1, 3,
        3, 3, 1, 1, 4, 2, 3, 2], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.20it/s]

epoch:  8 loss:  0.013277019374072552
tensor([4, 1, 2, 3, 3, 3, 1, 2, 1, 2, 3, 3, 0, 2, 3, 2, 1, 3, 3, 4, 2, 1, 4, 3,
        4, 1, 1, 4, 4, 2, 3, 3], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.24it/s]

epoch:  8 loss:  0.012136012315750122
tensor([3, 3, 3, 2, 4, 4, 2, 2, 2, 3, 1, 0, 3, 4, 4, 2, 4, 1, 0, 4, 1, 3, 0, 1,
        2, 4, 3, 3, 3, 1, 1, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.20it/s]

epoch:  8 loss:  0.01368465181440115
tensor([3, 0, 2, 0, 4, 3], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.33it/s]


epoch:  8 loss:  0.020639054477214813


100%|██████████| 5/5 [00:01<00:00,  3.71it/s]


              precision    recall  f1-score   support

           0       0.43      0.40      0.41        15
           1       0.30      0.26      0.28        23
           2       0.41      0.51      0.46        35
           3       0.43      0.56      0.49        32
           4       0.65      0.37      0.47        35

    accuracy                           0.44       140
   macro avg       0.44      0.42      0.42       140
weighted avg       0.46      0.44      0.43       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 2, 2, 3, 4, 3, 2, 4, 4, 3, 3, 2, 3, 4, 3, 4, 3, 1, 2, 4, 1, 0, 3, 2,
        4, 2, 4, 1, 4, 3, 0, 1], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.67it/s]

epoch:  9 loss:  0.011775780469179153
tensor([2, 2, 2, 4, 1, 4, 2, 3, 2, 1, 4, 3, 3, 4, 4, 3, 0, 3, 3, 4, 1, 2, 2, 3,
        4, 2, 1, 2, 4, 2, 2, 1], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.62it/s]

epoch:  9 loss:  0.011425373144447803
tensor([2, 1, 0, 3, 1, 0, 0, 0, 3, 2, 0, 1, 3, 3, 0, 4, 2, 4, 3, 3, 0, 3, 3, 3,
        2, 4, 0, 1, 4, 0, 2, 4], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.37it/s]

epoch:  9 loss:  0.01498540211468935
tensor([3, 2, 0, 0, 3, 0, 2, 1, 1, 3, 3, 2, 2, 3, 1, 3, 1, 4, 2, 4, 3, 4, 1, 1,
        2, 4, 1, 4, 3, 3, 0, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.26it/s]

epoch:  9 loss:  0.011945027858018875
tensor([4, 3, 2, 4, 0, 4, 2, 3, 1, 3, 3, 2, 2, 2, 0, 2, 1, 2, 3, 4, 3, 3, 4, 1,
        2, 2, 2, 2, 3, 4, 2, 1], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.28it/s]

epoch:  9 loss:  0.01046687737107277
tensor([4, 4, 4, 1, 1, 2, 3, 0, 4, 4, 3, 3, 4, 0, 0, 4, 4, 3, 2, 2, 2, 2, 1, 0,
        2, 2, 4, 2, 1, 2, 4, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.24it/s]

epoch:  9 loss:  0.012813192792236805
tensor([2, 1, 3, 3, 3, 4, 3, 1, 2, 1, 0, 2, 1, 4, 3, 4, 3, 4, 3, 4, 3, 3, 2, 3,
        3, 2, 3, 3, 4, 3, 2, 3], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.27it/s]

epoch:  9 loss:  0.009649048559367657
tensor([0, 1, 4, 2, 0, 1, 3, 0, 2, 2, 2, 3, 1, 3, 3, 2, 1, 4, 2, 2, 3, 4, 2, 2,
        3, 3, 2, 1, 1, 1, 1, 1], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.22it/s]

epoch:  9 loss:  0.011070989072322845
tensor([2, 4, 2, 4, 1, 2, 0, 4, 4, 0, 2, 1, 3, 2, 1, 4, 4, 2, 0, 2, 3, 0, 4, 0,
        3, 4, 0, 1, 2, 4, 3, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:06<00:01,  1.25it/s]

epoch:  9 loss:  0.012810860760509968
tensor([3, 1, 2, 4, 0, 1, 4, 2, 1, 3, 1, 3, 3, 3, 0, 4, 2, 0, 1, 3, 1, 2, 1, 3,
        1, 3, 2, 3, 3, 2, 3, 0], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.23it/s]

epoch:  9 loss:  0.010837877169251442
tensor([3, 4, 1, 2, 3, 3], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.34it/s]


epoch:  9 loss:  0.00723477965220809


100%|██████████| 5/5 [00:01<00:00,  3.66it/s]


              precision    recall  f1-score   support

           0       0.40      0.40      0.40        15
           1       0.28      0.22      0.24        23
           2       0.40      0.51      0.45        35
           3       0.49      0.56      0.52        32
           4       0.64      0.46      0.53        35

    accuracy                           0.45       140
   macro avg       0.44      0.43      0.43       140
weighted avg       0.46      0.45      0.45       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 1, 1, 2, 2, 4, 2, 4, 3, 3, 3, 2, 3, 0, 2, 3, 1, 0, 1, 4, 2, 1, 4, 3,
        1, 4, 2, 3, 2, 2, 3, 2], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.60it/s]

epoch:  10 loss:  0.009580925107002258
tensor([2, 1, 1, 2, 2, 2, 3, 2, 2, 1, 3, 2, 0, 2, 3, 3, 2, 3, 2, 4, 3, 1, 4, 4,
        1, 1, 2, 2, 4, 0, 2, 4], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.58it/s]

epoch:  10 loss:  0.009419758804142475
tensor([2, 0, 3, 0, 2, 4, 3, 1, 2, 3, 3, 2, 0, 1, 1, 3, 4, 3, 3, 4, 3, 4, 1, 3,
        3, 3, 2, 1, 1, 2, 3, 1], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.36it/s]

epoch:  10 loss:  0.009729643352329731
tensor([4, 1, 3, 1, 3, 1, 3, 0, 4, 3, 2, 1, 4, 3, 0, 2, 3, 3, 4, 4, 4, 4, 3, 4,
        4, 3, 2, 2, 2, 1, 2, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:03<00:05,  1.25it/s]

epoch:  10 loss:  0.009220617823302746
tensor([1, 4, 2, 4, 3, 4, 1, 2, 3, 1, 2, 1, 3, 3, 2, 1, 3, 4, 0, 2, 1, 3, 2, 4,
        1, 3, 3, 0, 2, 1, 2, 1], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.22it/s]

epoch:  10 loss:  0.00977930799126625
tensor([0, 2, 2, 4, 1, 3, 0, 4, 0, 3, 0, 2, 3, 1, 4, 1, 0, 1, 2, 3, 2, 2, 3, 1,
        3, 0, 3, 4, 0, 1, 1, 0], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.25it/s]

epoch:  10 loss:  0.011446785181760788
tensor([4, 3, 2, 4, 2, 2, 3, 4, 3, 1, 3, 3, 3, 3, 1, 2, 2, 0, 0, 4, 3, 0, 0, 2,
        0, 4, 1, 4, 2, 4, 2, 2], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.23it/s]

epoch:  10 loss:  0.009580293670296669
tensor([0, 2, 4, 4, 1, 4, 3, 2, 4, 3, 4, 0, 2, 2, 4, 3, 1, 0, 3, 3, 2, 3, 2, 0,
        3, 1, 3, 2, 1, 4, 2, 0], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.25it/s]

epoch:  10 loss:  0.009475691244006157
tensor([3, 2, 4, 4, 2, 4, 4, 3, 0, 4, 4, 2, 0, 3, 2, 4, 2, 1, 4, 2, 4, 4, 4, 0,
        3, 3, 4, 1, 2, 3, 2, 3], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.27it/s]

epoch:  10 loss:  0.009388075210154057
tensor([3, 4, 1, 3, 3, 0, 2, 2, 1, 3, 1, 0, 3, 2, 1, 4, 4, 4, 2, 0, 3, 4, 0, 4,
        3, 2, 1, 2, 3, 2, 1, 3], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.23it/s]

epoch:  10 loss:  0.009388112463057041
tensor([3, 3, 3, 4, 2, 3], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.33it/s]


epoch:  10 loss:  0.005487293470650911


100%|██████████| 5/5 [00:01<00:00,  4.03it/s]


              precision    recall  f1-score   support

           0       0.43      0.40      0.41        15
           1       0.32      0.26      0.29        23
           2       0.40      0.51      0.45        35
           3       0.46      0.56      0.51        32
           4       0.65      0.43      0.52        35

    accuracy                           0.45       140
   macro avg       0.45      0.43      0.43       140
weighted avg       0.47      0.45      0.45       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([4, 2, 1, 2, 3, 3, 1, 2, 3, 2, 4, 2, 2, 3, 1, 4, 4, 3, 3, 3, 1, 2, 4, 2,
        4, 4, 2, 3, 0, 0, 2, 2], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.60it/s]

epoch:  11 loss:  0.00787442922592163
tensor([2, 2, 2, 2, 2, 0, 4, 1, 3, 4, 2, 1, 0, 3, 3, 1, 4, 2, 4, 2, 3, 2, 1, 2,
        1, 0, 3, 2, 2, 4, 1, 4], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.58it/s]

epoch:  11 loss:  0.008137138560414314
tensor([0, 3, 4, 1, 1, 1, 3, 3, 1, 2, 4, 2, 0, 0, 4, 3, 2, 3, 4, 1, 3, 4, 2, 4,
        4, 0, 3, 2, 3, 0, 0, 2], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.35it/s]

epoch:  11 loss:  0.010306993499398232
tensor([3, 0, 2, 3, 2, 2, 3, 0, 4, 3, 4, 4, 2, 4, 3, 1, 3, 1, 2, 4, 4, 2, 1, 4,
        4, 3, 3, 2, 3, 3, 2, 3], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.26it/s]

epoch:  11 loss:  0.0074947429820895195
tensor([3, 3, 3, 3, 2, 1, 3, 2, 4, 1, 1, 3, 4, 1, 1, 2, 4, 4, 3, 2, 2, 3, 3, 4,
        1, 0, 4, 1, 4, 2, 4, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.27it/s]

epoch:  11 loss:  0.007720026653259993
tensor([0, 3, 2, 2, 4, 1, 0, 2, 4, 1, 0, 2, 4, 3, 1, 2, 4, 0, 3, 3, 2, 1, 3, 1,
        4, 4, 0, 0, 3, 2, 0, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.24it/s]

epoch:  11 loss:  0.00949033722281456
tensor([2, 2, 3, 0, 2, 4, 3, 4, 0, 1, 2, 3, 4, 1, 3, 3, 3, 1, 4, 2, 1, 3, 0, 1,
        3, 3, 3, 4, 3, 1, 3, 1], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.25it/s]

epoch:  11 loss:  0.0077652959153056145
tensor([1, 2, 4, 2, 4, 4, 3, 2, 3, 0, 4, 4, 1, 3, 1, 3, 3, 2, 2, 2, 3, 2, 4, 0,
        1, 2, 2, 2, 2, 0, 0, 0], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.22it/s]

epoch:  11 loss:  0.008323045447468758
tensor([4, 1, 4, 3, 1, 3, 2, 4, 0, 3, 4, 4, 1, 1, 3, 1, 1, 4, 4, 2, 3, 3, 2, 4,
        3, 0, 2, 3, 2, 2, 2, 4], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.24it/s]

epoch:  11 loss:  0.007792258635163307
tensor([2, 3, 1, 3, 0, 3, 1, 3, 2, 3, 1, 2, 2, 3, 3, 2, 0, 0, 1, 3, 3, 3, 1, 3,
        2, 4, 4, 2, 4, 0, 2, 1], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.27it/s]

epoch:  11 loss:  0.007604772225022316
tensor([3, 1, 2, 0, 3, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.33it/s]


epoch:  11 loss:  0.00672612339258194


100%|██████████| 5/5 [00:01<00:00,  3.92it/s]


              precision    recall  f1-score   support

           0       0.43      0.40      0.41        15
           1       0.33      0.26      0.29        23
           2       0.40      0.51      0.45        35
           3       0.49      0.56      0.52        32
           4       0.62      0.46      0.52        35

    accuracy                           0.46       140
   macro avg       0.45      0.44      0.44       140
weighted avg       0.47      0.46      0.46       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([3, 3, 2, 0, 3, 0, 1, 2, 2, 1, 4, 4, 1, 4, 0, 3, 4, 2, 1, 3, 1, 3, 4, 2,
        3, 3, 0, 3, 3, 3, 3, 0], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.63it/s]

epoch:  12 loss:  0.007593763060867786
tensor([2, 4, 2, 2, 4, 0, 4, 1, 4, 2, 2, 1, 0, 4, 2, 4, 3, 2, 2, 0, 3, 1, 1, 4,
        4, 2, 4, 2, 0, 4, 2, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:06,  1.47it/s]

epoch:  12 loss:  0.008149570785462856
tensor([4, 3, 2, 4, 3, 1, 3, 4, 1, 2, 3, 3, 4, 2, 4, 4, 3, 4, 4, 4, 2, 1, 1, 3,
        3, 1, 2, 3, 0, 4, 0, 4], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:06,  1.31it/s]

epoch:  12 loss:  0.007584235165268183
tensor([2, 0, 2, 1, 2, 3, 1, 3, 3, 0, 1, 4, 3, 4, 2, 2, 0, 2, 3, 4, 3, 4, 2, 0,
        3, 2, 1, 1, 0, 3, 2, 3], device='cuda:0')


 36%|███▋      | 4/11 [00:03<00:05,  1.24it/s]

epoch:  12 loss:  0.007260590326040983
tensor([3, 3, 3, 1, 1, 2, 2, 0, 2, 4, 4, 1, 3, 2, 4, 3, 2, 2, 4, 1, 4, 2, 2, 4,
        3, 4, 2, 2, 2, 1, 3, 3], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.27it/s]

epoch:  12 loss:  0.006337798200547695
tensor([0, 3, 1, 2, 1, 3, 4, 2, 0, 4, 0, 2, 3, 2, 2, 3, 3, 3, 1, 3, 0, 1, 3, 2,
        2, 4, 1, 2, 2, 4, 4, 3], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.28it/s]

epoch:  12 loss:  0.007028638850897551
tensor([1, 4, 4, 0, 3, 2, 3, 0, 4, 2, 3, 1, 4, 3, 1, 2, 4, 3, 2, 3, 3, 0, 2, 3,
        4, 1, 0, 2, 1, 1, 4, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.24it/s]

epoch:  12 loss:  0.007140002213418484
tensor([4, 4, 2, 3, 2, 3, 2, 4, 4, 4, 4, 1, 2, 0, 1, 2, 3, 3, 3, 3, 1, 2, 2, 2,
        0, 3, 2, 1, 1, 1, 0, 2], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.25it/s]

epoch:  12 loss:  0.007037855684757233
tensor([3, 0, 1, 3, 3, 2, 4, 1, 4, 4, 0, 3, 0, 3, 4, 1, 3, 0, 3, 2, 1, 3, 1, 1,
        2, 2, 2, 0, 0, 1, 2, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:06<00:01,  1.28it/s]

epoch:  12 loss:  0.007704028394073248
tensor([4, 2, 3, 3, 3, 1, 4, 4, 3, 1, 4, 1, 1, 1, 3, 3, 2, 2, 2, 2, 0, 1, 3, 3,
        4, 3, 3, 2, 3, 1, 2, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.23it/s]

epoch:  12 loss:  0.006414009258151054
tensor([2, 3, 3, 2, 0, 3], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.34it/s]


epoch:  12 loss:  0.005466740112751722


100%|██████████| 5/5 [00:01<00:00,  3.62it/s]


              precision    recall  f1-score   support

           0       0.43      0.40      0.41        15
           1       0.33      0.26      0.29        23
           2       0.40      0.51      0.45        35
           3       0.49      0.56      0.52        32
           4       0.62      0.46      0.52        35

    accuracy                           0.46       140
   macro avg       0.45      0.44      0.44       140
weighted avg       0.47      0.46      0.46       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 0, 1, 3, 0, 1, 4, 2, 2, 2, 1, 3, 3, 3, 1, 3, 2, 2, 0, 2, 3, 2, 1, 4,
        1, 2, 1, 3, 3, 1, 1, 0], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.98it/s]

epoch:  13 loss:  0.0064272768795490265
tensor([2, 2, 2, 3, 4, 1, 4, 1, 4, 0, 4, 3, 3, 2, 0, 2, 3, 3, 2, 1, 3, 1, 4, 3,
        0, 0, 4, 0, 1, 3, 4, 0], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.56it/s]

epoch:  13 loss:  0.007366783916950226
tensor([2, 4, 2, 3, 2, 1, 1, 2, 4, 1, 1, 2, 2, 2, 3, 4, 0, 1, 3, 2, 2, 4, 2, 1,
        4, 2, 2, 2, 3, 4, 0, 4], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.34it/s]

epoch:  13 loss:  0.006230952218174934
tensor([3, 1, 2, 2, 4, 4, 2, 3, 4, 3, 1, 1, 4, 0, 2, 3, 0, 3, 4, 2, 3, 2, 2, 3,
        1, 4, 4, 1, 4, 3, 2, 1], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.31it/s]

epoch:  13 loss:  0.00669889897108078
tensor([2, 0, 4, 0, 4, 3, 2, 3, 0, 3, 3, 1, 2, 1, 4, 0, 3, 4, 1, 2, 3, 3, 0, 3,
        3, 3, 3, 2, 1, 2, 0, 3], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.26it/s]

epoch:  13 loss:  0.006949686445295811
tensor([4, 0, 2, 3, 3, 2, 4, 2, 2, 2, 3, 4, 1, 3, 3, 2, 4, 4, 3, 3, 3, 1, 1, 3,
        4, 2, 4, 3, 3, 2, 2, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.27it/s]

epoch:  13 loss:  0.005403534509241581
tensor([1, 3, 1, 3, 2, 2, 3, 1, 4, 2, 3, 4, 3, 0, 0, 4, 3, 3, 0, 1, 3, 1, 2, 3,
        0, 4, 2, 0, 3, 4, 2, 0], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.22it/s]

epoch:  13 loss:  0.006523790303617716
tensor([3, 3, 4, 2, 0, 3, 1, 3, 4, 3, 4, 3, 1, 0, 3, 3, 3, 4, 2, 2, 4, 4, 1, 4,
        3, 2, 4, 4, 3, 2, 4, 4], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.25it/s]

epoch:  13 loss:  0.005704683717340231
tensor([2, 3, 2, 2, 0, 2, 2, 2, 4, 2, 4, 4, 2, 3, 4, 0, 0, 3, 1, 0, 3, 3, 1, 0,
        4, 2, 2, 4, 1, 2, 1, 1], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.22it/s]

epoch:  13 loss:  0.006849239580333233
tensor([4, 2, 0, 4, 0, 1, 2, 3, 2, 2, 1, 3, 4, 2, 3, 2, 4, 4, 1, 3, 4, 4, 1, 3,
        1, 4, 2, 1, 3, 2, 3, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.25it/s]

epoch:  13 loss:  0.005782831460237503
tensor([1, 3, 3, 2, 1, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.35it/s]


epoch:  13 loss:  0.005201574414968491


100%|██████████| 5/5 [00:01<00:00,  3.65it/s]


              precision    recall  f1-score   support

           0       0.43      0.40      0.41        15
           1       0.30      0.26      0.28        23
           2       0.40      0.51      0.45        35
           3       0.47      0.56      0.51        32
           4       0.65      0.43      0.52        35

    accuracy                           0.45       140
   macro avg       0.45      0.43      0.43       140
weighted avg       0.47      0.45      0.45       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([4, 0, 3, 4, 3, 3, 1, 3, 2, 4, 2, 3, 1, 3, 1, 2, 0, 2, 2, 3, 0, 2, 0, 2,
        4, 4, 1, 2, 2, 1, 3, 1], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.60it/s]

epoch:  14 loss:  0.006112642586231232
tensor([2, 1, 1, 0, 3, 4, 1, 4, 2, 3, 2, 3, 3, 3, 3, 4, 2, 3, 3, 4, 3, 4, 2, 0,
        4, 0, 4, 1, 4, 4, 1, 0], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.59it/s]

epoch:  14 loss:  0.006229893770068884
tensor([1, 2, 3, 2, 2, 2, 2, 2, 3, 3, 1, 0, 4, 3, 2, 2, 3, 0, 3, 3, 2, 4, 0, 3,
        2, 1, 1, 1, 2, 1, 3, 3], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.37it/s]

epoch:  14 loss:  0.0052536483854055405
tensor([3, 4, 2, 1, 2, 2, 4, 4, 4, 4, 3, 4, 1, 0, 4, 2, 1, 4, 3, 1, 2, 3, 2, 3,
        0, 0, 0, 4, 2, 3, 2, 3], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.27it/s]

epoch:  14 loss:  0.00587857561185956
tensor([4, 0, 2, 2, 4, 3, 0, 1, 4, 0, 1, 4, 0, 4, 3, 0, 2, 0, 1, 4, 2, 1, 3, 1,
        0, 2, 4, 4, 3, 2, 3, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.27it/s]

epoch:  14 loss:  0.0063978820107877254
tensor([2, 1, 4, 1, 3, 3, 2, 1, 3, 2, 4, 2, 1, 3, 1, 1, 0, 2, 4, 3, 2, 2, 2, 2,
        3, 3, 2, 4, 1, 0, 2, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.24it/s]

epoch:  14 loss:  0.005505746696144342
tensor([4, 3, 2, 3, 3, 3, 2, 1, 3, 4, 2, 0, 2, 1, 4, 2, 3, 3, 3, 4, 3, 3, 1, 4,
        4, 2, 1, 3, 1, 0, 3, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.25it/s]

epoch:  14 loss:  0.005258906167000532
tensor([0, 3, 3, 2, 3, 2, 3, 4, 1, 1, 1, 1, 4, 2, 2, 0, 4, 2, 3, 1, 3, 0, 4, 4,
        3, 2, 4, 3, 2, 3, 1, 0], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.22it/s]

epoch:  14 loss:  0.005763845052570105
tensor([4, 4, 2, 3, 3, 1, 1, 2, 4, 0, 2, 4, 4, 4, 4, 0, 3, 3, 3, 2, 2, 0, 4, 3,
        1, 3, 4, 2, 2, 1, 1, 1], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.25it/s]

epoch:  14 loss:  0.005789103452116251
tensor([2, 1, 3, 3, 2, 3, 3, 3, 0, 2, 3, 2, 2, 4, 3, 3, 2, 2, 3, 4, 4, 2, 3, 3,
        2, 3, 4, 4, 2, 1, 1, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.21it/s]

epoch:  14 loss:  0.0047111669555306435
tensor([1, 4, 0, 0, 2, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.33it/s]


epoch:  14 loss:  0.006780311930924654


100%|██████████| 5/5 [00:01<00:00,  3.68it/s]


              precision    recall  f1-score   support

           0       0.43      0.40      0.41        15
           1       0.30      0.26      0.28        23
           2       0.40      0.51      0.45        35
           3       0.49      0.56      0.52        32
           4       0.67      0.46      0.54        35

    accuracy                           0.46       140
   macro avg       0.46      0.44      0.44       140
weighted avg       0.47      0.46      0.46       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([4, 0, 1, 0, 2, 4, 3, 2, 2, 1, 3, 2, 2, 2, 0, 2, 3, 3, 1, 1, 3, 3, 1, 1,
        1, 4, 1, 1, 0, 4, 2, 3], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.67it/s]

epoch:  15 loss:  0.005610551219433546
tensor([4, 4, 2, 4, 4, 3, 1, 4, 0, 4, 3, 2, 4, 4, 3, 1, 1, 2, 0, 0, 3, 2, 1, 1,
        2, 2, 4, 3, 3, 3, 2, 4], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.57it/s]

epoch:  15 loss:  0.005732070654630661
tensor([0, 4, 3, 3, 3, 3, 1, 2, 1, 1, 3, 2, 1, 2, 2, 0, 0, 3, 4, 4, 2, 3, 1, 3,
        2, 4, 0, 3, 2, 3, 2, 3], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.35it/s]

epoch:  15 loss:  0.004943334963172674
tensor([4, 2, 3, 2, 0, 1, 1, 4, 1, 4, 1, 3, 2, 3, 4, 4, 3, 1, 0, 3, 2, 3, 3, 3,
        3, 0, 3, 4, 4, 4, 4, 3], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.27it/s]

epoch:  15 loss:  0.005029699299484491
tensor([3, 3, 4, 1, 4, 2, 4, 1, 0, 4, 4, 0, 3, 0, 1, 2, 3, 1, 3, 2, 1, 2, 2, 0,
        4, 1, 2, 1, 1, 4, 3, 1], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.28it/s]

epoch:  15 loss:  0.0059411185793578625
tensor([4, 3, 2, 0, 0, 4, 3, 4, 3, 2, 4, 2, 2, 4, 3, 3, 1, 2, 3, 2, 0, 3, 3, 2,
        2, 3, 0, 2, 2, 3, 1, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.28it/s]

epoch:  15 loss:  0.004631793592125177
tensor([2, 2, 4, 1, 4, 2, 4, 2, 4, 1, 2, 3, 2, 3, 3, 0, 2, 1, 2, 3, 4, 3, 3, 3,
        1, 2, 2, 0, 2, 3, 0, 2], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.23it/s]

epoch:  15 loss:  0.004888839554041624
tensor([2, 4, 4, 4, 2, 1, 1, 4, 4, 3, 1, 3, 1, 1, 3, 4, 2, 3, 1, 2, 2, 2, 4, 3,
        2, 2, 3, 1, 3, 1, 1, 4], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.20it/s]

epoch:  15 loss:  0.004808757454156876
tensor([2, 2, 3, 0, 2, 3, 4, 1, 2, 0, 1, 4, 4, 0, 3, 4, 2, 2, 0, 3, 2, 4, 3, 3,
        2, 2, 4, 4, 0, 0, 2, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.23it/s]

epoch:  15 loss:  0.005288994405418634
tensor([3, 4, 3, 3, 2, 1, 3, 3, 4, 0, 0, 0, 2, 3, 1, 3, 3, 0, 2, 3, 2, 4, 2, 3,
        4, 4, 1, 2, 2, 1, 2, 4], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.21it/s]

epoch:  15 loss:  0.004861756693571806
tensor([3, 2, 0, 3, 3, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.33it/s]


epoch:  15 loss:  0.004228619392961264


100%|██████████| 5/5 [00:01<00:00,  3.65it/s]


              precision    recall  f1-score   support

           0       0.43      0.40      0.41        15
           1       0.30      0.26      0.28        23
           2       0.40      0.51      0.45        35
           3       0.49      0.56      0.52        32
           4       0.67      0.46      0.54        35

    accuracy                           0.46       140
   macro avg       0.46      0.44      0.44       140
weighted avg       0.47      0.46      0.46       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 3, 2, 4, 2, 0, 1, 2, 3, 0, 2, 4, 2, 4, 2, 1, 2, 2, 2, 2, 3, 4, 4, 1,
        3, 4, 2, 1, 1, 1, 2, 1], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.60it/s]

epoch:  16 loss:  0.004482288844883442
tensor([0, 4, 0, 2, 3, 3, 3, 0, 2, 2, 2, 2, 2, 3, 4, 1, 3, 4, 4, 4, 3, 2, 1, 3,
        4, 3, 2, 2, 1, 4, 0, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.58it/s]

epoch:  16 loss:  0.004654584918171167
tensor([3, 2, 3, 3, 4, 1, 2, 1, 4, 1, 3, 3, 4, 3, 0, 4, 4, 2, 4, 2, 3, 1, 2, 3,
        4, 2, 0, 3, 3, 2, 2, 1], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.35it/s]

epoch:  16 loss:  0.004478076938539743
tensor([3, 1, 4, 1, 2, 0, 1, 3, 4, 4, 3, 0, 3, 4, 1, 0, 0, 4, 2, 3, 4, 3, 3, 1,
        1, 3, 4, 4, 2, 4, 2, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:03<00:05,  1.26it/s]

epoch:  16 loss:  0.005192482843995094
tensor([4, 4, 1, 0, 2, 4, 3, 3, 2, 3, 3, 4, 2, 1, 0, 0, 3, 2, 4, 4, 2, 3, 1, 2,
        2, 4, 3, 4, 2, 2, 3, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.28it/s]

epoch:  16 loss:  0.004657974001020193
tensor([2, 3, 2, 1, 1, 4, 2, 3, 3, 2, 4, 1, 0, 1, 4, 0, 0, 1, 3, 2, 2, 1, 3, 0,
        4, 4, 2, 0, 3, 3, 1, 3], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.24it/s]