# 电影评价分类（bert version）
> 五分类问题，和邮件垃圾的二分类类似


In [1]:
!conda env list


# conda environments:
#
base                  *  /opt/conda
federated_learning       /opt/conda/envs/federated_learning
python2                  /opt/conda/envs/python2
pytorch1.8               /opt/conda/envs/pytorch1.8
rapids                   /opt/conda/envs/rapids
tf1.14                   /opt/conda/envs/tf1.14
tf2.4.1                  /opt/conda/envs/tf2.4.1



## 1. 安装依赖

In [2]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertModel, BertForSequenceClassification
from tqdm import tqdm
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, classification_report
import wandb

/root/.local/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2022-05-08 00:04:39.243606: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64
2022-05-08 00:04:39.243727: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64
2022-05-08 00:04:39.243738: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing l

## 2. wandb初始化，设置device

In [3]:
!nvidia-smi
wandb.init(project="senti-analysis", entity='cocoshe', mode='disabled')
# wandb.config = {
#     'batch_size': 32,
#     'epochs': 5,
#     'lr': 5e-5,
#     'max_seq_length': 128,
# }
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

Sun May  8 00:04:44 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:3E:00.0 Off |                    0 |
| N/A   37C    P0    40W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.


## 3. 定义dataset

In [4]:
class MyDataset(Dataset):
    def __init__(self, df, model_name='bert-base-chinese'):
        self.data_df = df
        self.tokenizer = BertTokenizer.from_pretrained(model_name)

    def __len__(self):
        return len(self.data_df)

    def __getitem__(self, idx):
        input_text = self.data_df.iloc[idx, 0]
        label = self.data_df.iloc[idx, 1]

        tokenizer = self.tokenizer
        token = tokenizer(input_text, padding='max_length', truncation=True, max_length=128, return_tensors='pt', return_token_type_ids=False)
        input_ids = token['input_ids'].squeeze(0)
        attention_mask = token['attention_mask'].squeeze(0)
        label = np.int64(label)
        return input_ids.to(device), attention_mask.to(device), label

 ## 4. 拿tokenizer，实例化带classification head的bert

In [5]:
tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')
model = BertForSequenceClassification.from_pretrained('bert-base-chinese', num_labels=5)
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
epochs = 10

Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

 ## 5. 定义切分函数

In [6]:
def train_test_split(input_df, test_size=0.2, shuffle=True, random_state=None):
    if shuffle:
        input_df = input_df.sample(frac=1)
    ret_train_df = input_df[:int(len(input_df) * (1 - test_size))]
    ret_test_df = input_df[int(len(input_df) * (1 - test_size)):]
    return ret_train_df, ret_test_df

 ## 6. 映射字典，把label转换为数字

In [7]:
evaluate2score = {'力荐': '4', '推荐': '3', '还行': '2', '较差': '1', '很差': '0'}
score2evaluate = {4: '力荐', '3': '推荐', '2': '还行', '1': '较差', '0': '很差'}
evaluate_list = ['力荐', '推荐', '还行', '较差', '很差']
k, v = list(evaluate2score.items())[0]

 ## 7. 导入数据

In [8]:
# split train and test data directly(no need to split input and label, that's why not use sklearn.model_selection.train_test_split)
df = pd.read_csv('dataset/流浪地球.csv', encoding='utf-8', header=0, index_col=None, usecols=['content', 'evaluate'])
print(df.drop_duplicates(['evaluate'])['evaluate'])
df = df[df['evaluate'].isin(evaluate_list)]  # filter out the evaluate not in evaluate_list
print('after filter')
print(df.drop_duplicates(['evaluate'])['evaluate'])
df.head()

0                       推荐
2                       很差
3                       力荐
5                       还行
6                       较差
56     2019-02-05 23:16:40
96     2019-02-08 11:53:57
119    2019-02-09 09:14:52
161    2019-01-28 20:14:00
247    2019-02-10 23:30:50
261    2019-02-06 20:33:03
307    2019-02-06 15:31:25
339    2019-02-10 18:09:43
354    2019-02-08 05:09:17
395    2019-02-08 00:15:25
417    2019-02-09 18:32:26
431    2019-02-08 22:39:41
446    2019-02-07 19:41:14
463    2019-02-08 22:00:00
Name: evaluate, dtype: object
after filter
0    推荐
2    很差
3    力荐
5    还行
6    较差
Name: evaluate, dtype: object


content evaluate
0            一个悲伤的故事：太阳都要毁灭，地球都要流浪了，我国的校服还是这么丑......       推荐
1  电影比预期要更恢弘磅礴，晨昏线过后的永夜、火种计划、让地球流浪、木星推动地球…等等大小设定，...       推荐
2  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...       很差
3  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...       力荐
4  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...       很差

 ## 8. 把label转换为数字

In [9]:
df['evaluate'] = df['evaluate'].map(evaluate2score).astype(int)
print(df.dtypes)
df.head()

content     object
evaluate     int64
dtype: object


content  evaluate
0            一个悲伤的故事：太阳都要毁灭，地球都要流浪了，我国的校服还是这么丑......         3
1  电影比预期要更恢弘磅礴，晨昏线过后的永夜、火种计划、让地球流浪、木星推动地球…等等大小设定，...         3
2  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...         0
3  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...         4
4  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...         0

 ## 9. 切分训练集和测试集，装入loader

In [10]:
train_df, test_df = train_test_split(df, test_size=0.3, shuffle=True)

train_dataset = MyDataset(train_df, model_name='bert-base-chinese')
test_dataset = MyDataset(test_df, model_name='bert-base-chinese')

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

 ## 10. train

In [11]:
# train
def train():
    model.train()
    for epoch in range(epochs):
        for i, batch in enumerate(tqdm(train_loader)):
            input_ids, attention_mask, label = batch
            input_ids, attention_mask, label = input_ids.to(device), attention_mask.to(device), label.to(device)
            print(label)
            output = model(input_ids, attention_mask, labels=label)
            loss = output[0]

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            print('epoch: ', epoch, 'loss: ', loss.item())
            wandb.log({'epoch': epoch,'step': i, 'loss': loss.item()})

        evaluate()

 ## 11. evaluate

In [12]:
# evaluate
def evaluate():
    label_list = []
    pred_list = []
    model.eval()
    with torch.no_grad():
        model.eval()
        eval_steps = 0
        pred_list = []
        label_list = []
        for i, batch in enumerate(tqdm(test_loader)):
            input_ids, attention_mask, label = batch
            input_ids, attention_mask, label = input_ids.to(device), attention_mask.to(device), label.to(device)
            output = model(input_ids, attention_mask, labels=label)
            pred_list += (torch.argmax(output[1], dim=-1))
            label_list += label
            eval_steps += 1

        label_list, pred_list = [item.cpu().numpy() for item in label_list], [item.cpu().numpy() for item in pred_list]
        # f1 = f1_score(label_list, pred_list, average='macro')
        # acc = accuracy_score(label_list, pred_list)
        # precision = precision_score(label_list, pred_list, average='macro')
        # recall = recall_score(label_list, pred_list, average='macro')
        report = classification_report(label_list, pred_list)
        print(report)

In [13]:
train()
# evaluate()

  0%|          | 0/11 [00:00<?, ?it/s]

tensor([1, 3, 1, 4, 1, 1, 0, 2, 1, 4, 2, 2, 4, 0, 4, 4, 1, 2, 4, 2, 3, 4, 2, 0,
        4, 1, 2, 1, 2, 2, 3, 3], device='cuda:0')


  9%|▉         | 1/11 [00:01<00:12,  1.26s/it]

epoch:  0 loss:  1.6989562511444092
tensor([0, 3, 1, 3, 3, 4, 4, 4, 0, 1, 4, 1, 2, 4, 0, 3, 2, 1, 0, 4, 2, 2, 2, 1,
        1, 4, 3, 2, 2, 1, 2, 3], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:06,  1.31it/s]

epoch:  0 loss:  1.6197503805160522
tensor([2, 4, 2, 2, 1, 1, 4, 4, 4, 0, 0, 4, 1, 2, 2, 4, 4, 3, 1, 1, 4, 4, 2, 0,
        4, 2, 1, 4, 1, 1, 4, 2], device='cuda:0')


 27%|██▋       | 3/11 [00:01<00:04,  1.82it/s]

epoch:  0 loss:  1.4003405570983887
tensor([1, 0, 3, 1, 1, 4, 1, 0, 4, 2, 2, 2, 0, 2, 1, 4, 3, 1, 4, 1, 2, 2, 2, 2,
        2, 1, 2, 1, 0, 1, 1, 3], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:03,  2.20it/s]

epoch:  0 loss:  1.5048171281814575
tensor([1, 4, 3, 3, 0, 1, 3, 2, 4, 3, 3, 0, 2, 2, 2, 3, 3, 3, 3, 1, 3, 2, 2, 2,
        3, 3, 3, 2, 3, 3, 4, 3], device='cuda:0')


 45%|████▌     | 5/11 [00:02<00:02,  2.50it/s]

epoch:  0 loss:  1.6969808340072632
tensor([4, 2, 2, 2, 3, 2, 4, 2, 0, 4, 3, 0, 0, 2, 4, 0, 3, 2, 1, 2, 0, 2, 1, 2,
        2, 3, 3, 2, 0, 3, 3, 4], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:05,  1.05s/it]

epoch:  0 loss:  1.7051517963409424
tensor([3, 3, 4, 2, 3, 1, 4, 3, 0, 0, 3, 3, 4, 4, 2, 2, 2, 1, 1, 3, 0, 2, 3, 3,
        4, 3, 3, 2, 2, 3, 4, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.00it/s]

epoch:  0 loss:  1.6950457096099854
tensor([4, 2, 2, 0, 2, 3, 4, 4, 1, 4, 2, 4, 3, 2, 0, 3, 4, 2, 1, 4, 2, 3, 2, 3,
        1, 4, 1, 3, 2, 3, 3, 4], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.09it/s]

epoch:  0 loss:  1.6250977516174316
tensor([0, 3, 3, 2, 3, 3, 1, 3, 2, 1, 0, 4, 4, 2, 4, 4, 2, 2, 3, 0, 3, 2, 4, 4,
        4, 3, 2, 3, 3, 3, 2, 4], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.15it/s]

epoch:  0 loss:  1.5681312084197998
tensor([3, 0, 4, 0, 0, 4, 2, 2, 3, 4, 2, 2, 3, 0, 2, 1, 3, 2, 2, 3, 1, 3, 3, 3,
        4, 4, 1, 2, 1, 1, 1, 3], device='cuda:0')


 91%|█████████ | 10/11 [00:08<00:00,  1.14it/s]

epoch:  0 loss:  1.597650170326233
tensor([4, 2, 4, 1, 3, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.28it/s]


epoch:  0 loss:  1.278067708015442


100%|██████████| 5/5 [00:01<00:00,  3.89it/s]
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           1       0.00      0.00      0.00        23
           2       0.48      0.37      0.42        30
           3       0.32      0.75      0.44        40
           4       0.43      0.30      0.35        30

    accuracy                           0.36       140
   macro avg       0.24      0.28      0.24       140
weighted avg       0.28      0.36      0.29       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([0, 0, 0, 3, 1, 2, 2, 1, 2, 3, 0, 4, 1, 3, 1, 3, 4, 2, 0, 3, 2, 4, 3, 0,
        2, 3, 2, 1, 3, 4, 2, 1], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.69it/s]

epoch:  1 loss:  1.6452566385269165
tensor([2, 4, 2, 0, 3, 2, 2, 1, 1, 2, 3, 4, 0, 3, 4, 2, 3, 1, 4, 2, 3, 3, 4, 2,
        0, 2, 2, 2, 0, 0, 2, 4], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.63it/s]

epoch:  1 loss:  1.47101891040802
tensor([3, 1, 3, 2, 2, 3, 4, 2, 3, 2, 1, 1, 3, 2, 1, 2, 3, 4, 2, 1, 3, 2, 1, 2,
        4, 3, 2, 3, 3, 2, 1, 4], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.36it/s]

epoch:  1 loss:  1.550919771194458
tensor([1, 3, 3, 4, 1, 1, 0, 4, 4, 0, 2, 1, 4, 3, 2, 3, 1, 3, 4, 1, 4, 2, 3, 1,
        4, 3, 3, 4, 2, 2, 2, 1], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.26it/s]

epoch:  1 loss:  1.6433032751083374
tensor([3, 2, 3, 1, 0, 4, 1, 2, 1, 4, 2, 3, 3, 0, 3, 4, 0, 2, 2, 3, 2, 1, 0, 2,
        4, 4, 4, 3, 1, 3, 1, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.27it/s]

epoch:  1 loss:  1.5182944536209106
tensor([3, 4, 2, 4, 1, 2, 2, 2, 4, 2, 3, 3, 3, 2, 4, 3, 2, 0, 2, 2, 0, 0, 2, 3,
        3, 1, 1, 0, 1, 4, 1, 4], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.30it/s]

epoch:  1 loss:  1.4211496114730835
tensor([1, 3, 0, 4, 4, 4, 2, 4, 4, 4, 0, 4, 2, 2, 1, 0, 0, 3, 2, 1, 2, 3, 3, 1,
        1, 3, 3, 4, 4, 4, 1, 2], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.30it/s]

epoch:  1 loss:  1.504536509513855
tensor([4, 0, 2, 2, 2, 3, 1, 2, 3, 1, 3, 4, 2, 4, 3, 4, 2, 1, 1, 1, 3, 3, 2, 2,
        4, 4, 1, 4, 4, 4, 1, 4], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.20it/s]

epoch:  1 loss:  1.5207475423812866
tensor([3, 2, 2, 4, 1, 4, 1, 2, 3, 2, 0, 2, 3, 1, 0, 3, 3, 2, 4, 2, 4, 3, 2, 3,
        2, 2, 0, 3, 2, 3, 0, 3], device='cuda:0')


 82%|████████▏ | 9/11 [00:06<00:01,  1.23it/s]

epoch:  1 loss:  1.4634615182876587
tensor([2, 2, 1, 2, 4, 1, 2, 2, 2, 0, 3, 2, 2, 0, 4, 3, 2, 4, 4, 3, 4, 4, 3, 4,
        3, 4, 4, 4, 4, 0, 1, 1], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.27it/s]

epoch:  1 loss:  1.3924728631973267
tensor([3, 3, 3, 0, 4, 3], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.36it/s]


epoch:  1 loss:  1.5151160955429077


100%|██████████| 5/5 [00:01<00:00,  3.59it/s]
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           1       0.44      0.17      0.25        23
           2       0.25      0.13      0.17        30
           3       0.25      0.40      0.31        40
           4       0.27      0.47      0.35        30

    accuracy                           0.27       140
   macro avg       0.24      0.23      0.22       140
weighted avg       0.26      0.27      0.24       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 2, 3, 2, 3, 2, 2, 1, 4, 3, 0, 4, 4, 1, 2, 2, 3, 1, 2, 1, 0, 2, 4, 2,
        2, 3, 4, 2, 1, 0, 2, 1], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.64it/s]

epoch:  2 loss:  1.3892436027526855
tensor([0, 1, 1, 4, 2, 1, 3, 4, 4, 2, 1, 3, 0, 2, 4, 3, 1, 2, 4, 2, 3, 0, 2, 3,
        4, 2, 3, 2, 4, 4, 3, 3], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.60it/s]

epoch:  2 loss:  1.2646783590316772
tensor([3, 3, 2, 2, 2, 4, 1, 3, 3, 1, 0, 2, 3, 1, 1, 3, 3, 3, 1, 1, 4, 2, 2, 2,
        2, 0, 2, 3, 4, 2, 2, 3], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.45it/s]

epoch:  2 loss:  1.3367840051651
tensor([3, 1, 4, 4, 2, 1, 3, 4, 3, 2, 3, 3, 1, 4, 3, 2, 4, 4, 3, 0, 4, 1, 2, 0,
        0, 3, 0, 2, 4, 2, 4, 2], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.30it/s]

epoch:  2 loss:  1.3593592643737793
tensor([3, 0, 0, 2, 0, 2, 3, 3, 3, 1, 4, 4, 2, 2, 4, 2, 4, 3, 3, 2, 2, 4, 1, 3,
        1, 3, 2, 3, 4, 1, 3, 0], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.26it/s]

epoch:  2 loss:  1.2035294771194458
tensor([3, 3, 1, 1, 3, 0, 1, 4, 3, 4, 0, 2, 1, 2, 1, 4, 3, 0, 3, 3, 1, 3, 2, 1,
        4, 4, 0, 2, 4, 0, 1, 2], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.27it/s]

epoch:  2 loss:  1.2512143850326538
tensor([1, 1, 0, 4, 2, 4, 3, 1, 1, 1, 3, 2, 2, 2, 4, 4, 3, 2, 4, 2, 0, 2, 3, 0,
        4, 0, 4, 1, 4, 2, 3, 0], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.23it/s]

epoch:  2 loss:  1.2850522994995117
tensor([3, 3, 4, 0, 2, 3, 3, 3, 2, 4, 2, 1, 3, 2, 3, 3, 1, 4, 2, 0, 1, 2, 1, 3,
        0, 3, 2, 2, 0, 3, 2, 4], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.26it/s]

epoch:  2 loss:  1.163034439086914
tensor([4, 1, 4, 3, 1, 2, 4, 0, 0, 3, 1, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4, 4, 2, 3,
        2, 2, 2, 4, 2, 3, 2, 0], device='cuda:0')


 82%|████████▏ | 9/11 [00:06<00:01,  1.28it/s]

epoch:  2 loss:  1.1486557722091675
tensor([1, 4, 1, 3, 3, 1, 4, 2, 2, 3, 3, 4, 4, 0, 3, 2, 1, 3, 4, 4, 1, 4, 2, 2,
        3, 2, 1, 1, 3, 4, 1, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.23it/s]

epoch:  2 loss:  1.203857183456421
tensor([2, 1, 2, 2, 2, 3], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.35it/s]


epoch:  2 loss:  0.9669663906097412


100%|██████████| 5/5 [00:01<00:00,  3.98it/s]


              precision    recall  f1-score   support

           0       0.67      0.12      0.20        17
           1       1.00      0.13      0.23        23
           2       0.30      0.97      0.46        30
           3       0.38      0.12      0.19        40
           4       0.44      0.37      0.40        30

    accuracy                           0.36       140
   macro avg       0.56      0.34      0.30       140
weighted avg       0.51      0.36      0.30       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 2, 2, 2, 3, 3, 2, 4, 4, 1, 4, 4, 4, 3, 1, 3, 4, 3, 2, 3, 0, 1, 2, 0,
        4, 2, 4, 2, 3, 0, 3, 4], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.68it/s]

epoch:  3 loss:  0.94598788022995
tensor([2, 1, 2, 4, 3, 3, 2, 4, 4, 4, 2, 2, 2, 1, 3, 3, 1, 2, 2, 3, 1, 3, 2, 0,
        4, 3, 2, 4, 2, 0, 3, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.60it/s]

epoch:  3 loss:  0.7953845262527466
tensor([3, 2, 4, 3, 3, 2, 3, 3, 4, 2, 2, 2, 3, 3, 2, 2, 0, 1, 3, 3, 4, 4, 0, 2,
        0, 1, 2, 0, 0, 3, 4, 3], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.37it/s]

epoch:  3 loss:  0.8355575203895569
tensor([1, 2, 2, 2, 3, 1, 3, 4, 2, 2, 2, 3, 2, 2, 4, 2, 4, 2, 1, 2, 1, 2, 3, 4,
        3, 3, 4, 0, 1, 1, 1, 1], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.27it/s]

epoch:  3 loss:  0.831500232219696
tensor([1, 1, 4, 4, 3, 0, 0, 3, 1, 1, 2, 4, 2, 0, 0, 3, 0, 0, 4, 2, 2, 0, 2, 1,
        4, 4, 2, 2, 2, 2, 3, 3], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.29it/s]

epoch:  3 loss:  0.8161143064498901
tensor([3, 1, 1, 3, 1, 3, 3, 4, 3, 2, 3, 1, 4, 2, 3, 2, 1, 2, 4, 2, 1, 3, 1, 2,
        3, 4, 1, 2, 1, 3, 4, 3], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.24it/s]

epoch:  3 loss:  0.8235730528831482
tensor([0, 4, 2, 3, 1, 1, 2, 0, 1, 2, 0, 4, 3, 2, 4, 3, 3, 3, 4, 2, 1, 1, 1, 0,
        2, 0, 4, 1, 4, 4, 1, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.25it/s]

epoch:  3 loss:  1.000657558441162
tensor([4, 4, 0, 0, 1, 4, 3, 1, 4, 0, 2, 3, 4, 1, 2, 2, 1, 2, 2, 2, 3, 0, 4, 3,
        3, 3, 1, 4, 0, 3, 3, 2], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.23it/s]

epoch:  3 loss:  0.7627633213996887
tensor([1, 3, 2, 4, 4, 4, 4, 2, 2, 1, 3, 4, 2, 1, 3, 3, 3, 3, 2, 4, 0, 1, 1, 2,
        4, 0, 2, 0, 1, 0, 4, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:06<00:01,  1.25it/s]

epoch:  3 loss:  0.8421412706375122
tensor([4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 3, 3, 4, 3, 0, 4, 4, 3, 1, 2, 3, 1, 3, 4,
        1, 3, 1, 2, 3, 3, 4, 3], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.22it/s]

epoch:  3 loss:  0.7041587233543396
tensor([0, 4, 4, 1, 2, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.34it/s]


epoch:  3 loss:  0.9436371922492981


100%|██████████| 5/5 [00:01<00:00,  4.03it/s]
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/root/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           1       0.43      0.26      0.32        23
           2       0.31      0.90      0.46        30
           3       0.47      0.20      0.28        40
           4       0.41      0.30      0.35        30

    accuracy                           0.36       140
   macro avg       0.32      0.33      0.28       140
weighted avg       0.36      0.36      0.31       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 3, 0, 4, 1, 2, 1, 1, 3, 2, 2, 4, 3, 2, 2, 2, 0, 2, 1, 1, 4, 4, 2, 1,
        4, 2, 1, 2, 2, 3, 2, 1], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:04,  2.01it/s]

epoch:  4 loss:  0.6278772354125977
tensor([1, 4, 3, 2, 1, 4, 3, 1, 1, 4, 0, 1, 2, 3, 3, 2, 3, 4, 0, 1, 3, 2, 1, 2,
        0, 4, 0, 2, 2, 4, 3, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.74it/s]

epoch:  4 loss:  0.5655576586723328
tensor([0, 4, 4, 1, 1, 3, 2, 3, 1, 3, 1, 2, 2, 2, 3, 4, 1, 4, 0, 4, 2, 2, 1, 1,
        1, 2, 4, 2, 3, 0, 3, 3], device='cuda:0')


 27%|██▋       | 3/11 [00:01<00:05,  1.41it/s]

epoch:  4 loss:  0.4544612467288971
tensor([2, 2, 3, 0, 3, 2, 2, 2, 1, 3, 3, 1, 2, 3, 4, 2, 4, 4, 2, 2, 2, 3, 1, 0,
        0, 4, 4, 3, 3, 0, 2, 4], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.29it/s]

epoch:  4 loss:  0.5075749158859253
tensor([2, 3, 3, 1, 2, 3, 2, 0, 4, 4, 4, 0, 3, 0, 0, 3, 4, 4, 1, 1, 3, 4, 1, 2,
        2, 2, 3, 0, 0, 1, 2, 4], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.23it/s]

epoch:  4 loss:  0.673913300037384
tensor([3, 2, 4, 2, 0, 2, 4, 4, 0, 2, 4, 1, 3, 2, 3, 2, 4, 4, 3, 4, 4, 2, 3, 2,
        4, 0, 2, 3, 3, 0, 3, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.20it/s]

epoch:  4 loss:  0.6255579590797424
tensor([4, 2, 4, 4, 3, 3, 3, 4, 2, 3, 4, 3, 0, 4, 0, 4, 3, 2, 2, 3, 4, 0, 3, 0,
        4, 3, 1, 3, 2, 0, 2, 2], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.18it/s]

epoch:  4 loss:  0.42625871300697327
tensor([4, 4, 2, 0, 2, 1, 4, 3, 4, 2, 3, 0, 3, 4, 2, 2, 1, 1, 4, 4, 2, 3, 1, 3,
        4, 1, 4, 2, 3, 3, 1, 3], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.21it/s]

epoch:  4 loss:  0.5042048096656799
tensor([3, 2, 2, 3, 1, 1, 3, 2, 3, 2, 3, 4, 3, 2, 1, 2, 0, 4, 2, 0, 2, 2, 3, 0,
        3, 3, 1, 1, 4, 3, 4, 1], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.18it/s]

epoch:  4 loss:  0.5337257981300354
tensor([3, 2, 2, 4, 3, 2, 4, 0, 3, 4, 1, 3, 3, 2, 3, 1, 4, 3, 2, 4, 1, 4, 4, 2,
        1, 1, 4, 4, 3, 2, 2, 3], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.22it/s]

epoch:  4 loss:  0.4681510925292969
tensor([1, 2, 2, 1, 1, 1], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.32it/s]


epoch:  4 loss:  0.9668617248535156


100%|██████████| 5/5 [00:01<00:00,  3.63it/s]


              precision    recall  f1-score   support

           0       0.40      0.12      0.18        17
           1       0.44      0.48      0.46        23
           2       0.40      0.70      0.51        30
           3       0.49      0.57      0.53        40
           4       0.50      0.17      0.25        30

    accuracy                           0.44       140
   macro avg       0.45      0.41      0.38       140
weighted avg       0.45      0.44      0.41       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([4, 3, 1, 2, 3, 3, 2, 2, 3, 3, 4, 2, 3, 2, 4, 3, 4, 2, 1, 4, 1, 4, 4, 3,
        1, 1, 0, 3, 3, 3, 1, 2], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.63it/s]

epoch:  5 loss:  0.31042972207069397
tensor([1, 2, 3, 4, 2, 4, 2, 4, 0, 3, 1, 4, 4, 0, 1, 2, 1, 2, 1, 3, 3, 2, 2, 3,
        1, 1, 2, 4, 1, 0, 2, 4], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:06,  1.45it/s]

epoch:  5 loss:  0.362885445356369
tensor([2, 3, 0, 3, 1, 3, 3, 2, 1, 1, 2, 3, 0, 0, 4, 4, 0, 1, 3, 4, 1, 2, 0, 1,
        1, 2, 4, 3, 2, 4, 4, 1], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.37it/s]

epoch:  5 loss:  0.4219624102115631
tensor([3, 3, 4, 2, 3, 2, 3, 0, 4, 2, 3, 2, 3, 0, 0, 1, 0, 3, 2, 2, 2, 1, 2, 0,
        2, 2, 1, 4, 0, 2, 2, 1], device='cuda:0')


 36%|███▋      | 4/11 [00:03<00:05,  1.27it/s]

epoch:  5 loss:  0.5436050295829773
tensor([3, 3, 3, 2, 1, 2, 2, 4, 1, 2, 4, 2, 3, 4, 3, 4, 2, 2, 1, 2, 2, 4, 4, 3,
        3, 2, 4, 2, 1, 4, 2, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.29it/s]

epoch:  5 loss:  0.32716721296310425
tensor([0, 1, 3, 4, 4, 4, 4, 4, 4, 2, 4, 2, 3, 1, 4, 3, 2, 2, 0, 3, 1, 3, 3, 2,
        3, 1, 1, 3, 3, 0, 3, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.23it/s]

epoch:  5 loss:  0.25545069575309753
tensor([2, 2, 2, 3, 2, 2, 3, 0, 2, 2, 2, 4, 2, 2, 4, 1, 2, 2, 3, 4, 1, 1, 2, 1,
        1, 1, 2, 3, 2, 4, 4, 0], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.20it/s]

epoch:  5 loss:  0.17163003981113434
tensor([3, 0, 0, 4, 3, 4, 3, 3, 2, 1, 4, 2, 4, 4, 1, 2, 2, 4, 4, 3, 4, 4, 3, 2,
        4, 0, 0, 2, 2, 4, 0, 0], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.23it/s]

epoch:  5 loss:  0.35536855459213257
tensor([0, 1, 2, 3, 2, 3, 2, 4, 1, 3, 1, 3, 4, 0, 1, 3, 3, 0, 1, 3, 0, 3, 3, 3,
        4, 2, 4, 0, 4, 3, 2, 4], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.21it/s]

epoch:  5 loss:  0.3184170424938202
tensor([1, 3, 2, 3, 1, 1, 3, 2, 1, 1, 4, 0, 2, 4, 4, 3, 3, 4, 0, 2, 4, 2, 4, 4,
        3, 0, 3, 2, 4, 2, 3, 1], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.24it/s]

epoch:  5 loss:  0.3122996687889099
tensor([2, 2, 4, 3, 3, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.33it/s]


epoch:  5 loss:  0.14402087032794952


100%|██████████| 5/5 [00:01<00:00,  3.98it/s]


              precision    recall  f1-score   support

           0       0.38      0.35      0.36        17
           1       0.40      0.17      0.24        23
           2       0.33      0.87      0.48        30
           3       0.55      0.45      0.49        40
           4       0.50      0.03      0.06        30

    accuracy                           0.39       140
   macro avg       0.43      0.38      0.33       140
weighted avg       0.44      0.39      0.34       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([1, 1, 1, 4, 2, 2, 4, 2, 1, 4, 4, 2, 4, 4, 4, 2, 4, 0, 3, 2, 2, 3, 2, 2,
        4, 2, 3, 3, 3, 4, 2, 4], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.66it/s]

epoch:  6 loss:  0.18459804356098175
tensor([1, 3, 2, 2, 2, 1, 2, 3, 1, 4, 1, 0, 1, 1, 0, 2, 2, 2, 3, 4, 4, 3, 3, 0,
        3, 4, 1, 2, 1, 1, 0, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:06,  1.48it/s]

epoch:  6 loss:  0.25973454117774963
tensor([0, 3, 1, 2, 2, 2, 4, 4, 2, 3, 0, 3, 3, 3, 0, 2, 3, 1, 1, 4, 2, 4, 0, 1,
        1, 0, 0, 4, 1, 4, 2, 4], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.39it/s]

epoch:  6 loss:  0.21092170476913452
tensor([3, 1, 3, 4, 1, 2, 3, 3, 0, 2, 4, 2, 1, 0, 3, 1, 3, 3, 0, 1, 2, 4, 2, 2,
        3, 0, 0, 3, 1, 3, 3, 1], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.29it/s]

epoch:  6 loss:  0.17691676318645477
tensor([4, 3, 1, 2, 3, 4, 4, 3, 2, 3, 2, 3, 2, 1, 0, 4, 2, 1, 1, 0, 1, 2, 2, 3,
        2, 2, 3, 3, 3, 4, 1, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.24it/s]

epoch:  6 loss:  0.12007638067007065
tensor([3, 3, 2, 0, 4, 3, 4, 4, 0, 3, 3, 0, 2, 2, 1, 0, 4, 3, 1, 1, 3, 1, 3, 3,
        0, 2, 4, 2, 1, 2, 3, 3], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:03,  1.26it/s]

epoch:  6 loss:  0.09640800207853317
tensor([0, 2, 2, 4, 4, 0, 0, 3, 2, 3, 3, 3, 4, 1, 4, 4, 2, 4, 3, 4, 2, 2, 4, 3,
        1, 4, 2, 4, 1, 3, 2, 1], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.28it/s]

epoch:  6 loss:  0.16319088637828827
tensor([2, 2, 1, 4, 0, 1, 0, 2, 3, 4, 3, 2, 3, 1, 3, 0, 2, 4, 4, 2, 1, 2, 3, 1,
        4, 2, 2, 2, 2, 4, 1, 4], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.24it/s]

epoch:  6 loss:  0.16833148896694183
tensor([0, 1, 2, 2, 2, 4, 3, 4, 4, 2, 4, 1, 2, 0, 4, 3, 3, 2, 4, 2, 4, 4, 3, 2,
        1, 0, 2, 2, 3, 3, 1, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.21it/s]

epoch:  6 loss:  0.07632781565189362
tensor([4, 4, 3, 2, 4, 3, 4, 4, 1, 4, 0, 4, 3, 3, 2, 0, 4, 2, 2, 4, 3, 3, 2, 2,
        1, 2, 2, 1, 3, 2, 1, 3], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.19it/s]

epoch:  6 loss:  0.07293114066123962
tensor([3, 3, 4, 3, 3, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.32it/s]


epoch:  6 loss:  0.1296992152929306


100%|██████████| 5/5 [00:01<00:00,  3.58it/s]


              precision    recall  f1-score   support

           0       0.50      0.24      0.32        17
           1       0.38      0.52      0.44        23
           2       0.47      0.50      0.48        30
           3       0.42      0.38      0.39        40
           4       0.31      0.33      0.32        30

    accuracy                           0.40       140
   macro avg       0.41      0.39      0.39       140
weighted avg       0.41      0.40      0.40       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([1, 0, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 1, 3, 4, 0, 2, 2, 3, 3, 2, 3, 4,
        1, 3, 4, 0, 3, 2, 3, 4], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.64it/s]

epoch:  7 loss:  0.1287415474653244
tensor([1, 4, 4, 4, 3, 3, 4, 4, 2, 2, 4, 3, 3, 1, 3, 2, 4, 0, 1, 1, 0, 3, 3, 2,
        4, 2, 1, 1, 3, 4, 4, 2], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.58it/s]

epoch:  7 loss:  0.04331682622432709
tensor([1, 4, 0, 4, 3, 3, 3, 2, 2, 1, 4, 3, 3, 0, 3, 4, 0, 4, 3, 1, 2, 2, 2, 4,
        3, 1, 2, 3, 4, 2, 2, 4], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.35it/s]

epoch:  7 loss:  0.10073807090520859
tensor([2, 2, 4, 2, 3, 3, 1, 2, 2, 1, 4, 4, 2, 2, 3, 2, 0, 1, 4, 1, 1, 2, 4, 3,
        2, 1, 1, 1, 1, 0, 2, 4], device='cuda:0')


 36%|███▋      | 4/11 [00:03<00:05,  1.26it/s]

epoch:  7 loss:  0.058759838342666626
tensor([2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 4, 4, 4, 0, 2, 2, 0, 2, 3, 3, 1, 1, 2, 3,
        1, 2, 2, 2, 4, 4, 1, 3], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.22it/s]

epoch:  7 loss:  0.05474207177758217
tensor([2, 1, 3, 0, 0, 0, 3, 2, 4, 3, 0, 0, 3, 3, 2, 3, 3, 2, 3, 0, 3, 2, 2, 1,
        3, 1, 3, 4, 3, 4, 3, 1], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.23it/s]

epoch:  7 loss:  0.08094903081655502
tensor([2, 2, 4, 0, 4, 2, 2, 4, 1, 2, 2, 1, 4, 2, 3, 0, 3, 3, 4, 1, 3, 0, 4, 1,
        4, 4, 3, 2, 2, 4, 3, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.26it/s]

epoch:  7 loss:  0.0951613262295723
tensor([1, 3, 4, 0, 2, 3, 4, 2, 1, 4, 2, 2, 2, 0, 4, 2, 0, 0, 1, 3, 4, 3, 0, 4,
        2, 3, 2, 1, 2, 1, 2, 1], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.23it/s]

epoch:  7 loss:  0.12161365896463394
tensor([3, 2, 1, 3, 4, 1, 0, 3, 0, 1, 4, 4, 2, 3, 2, 4, 0, 1, 1, 0, 4, 3, 3, 2,
        2, 3, 3, 2, 4, 4, 4, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.25it/s]

epoch:  7 loss:  0.11339304596185684
tensor([3, 2, 2, 2, 2, 3, 3, 1, 1, 1, 1, 4, 0, 2, 4, 3, 4, 2, 1, 4, 3, 2, 0, 4,
        2, 3, 2, 0, 2, 3, 3, 2], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.27it/s]

epoch:  7 loss:  0.03913959115743637
tensor([0, 3, 1, 2, 4, 1], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.34it/s]


epoch:  7 loss:  0.15421676635742188


100%|██████████| 5/5 [00:01<00:00,  3.68it/s]


              precision    recall  f1-score   support

           0       0.42      0.29      0.34        17
           1       0.44      0.30      0.36        23
           2       0.34      0.80      0.48        30
           3       0.46      0.15      0.23        40
           4       0.36      0.33      0.34        30

    accuracy                           0.37       140
   macro avg       0.40      0.38      0.35       140
weighted avg       0.40      0.37      0.34       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 2, 4, 4, 2, 3, 4, 1, 4, 4, 1, 3, 1, 1, 4, 3, 3, 2, 2, 4, 2, 3, 3, 2,
        3, 2, 2, 4, 4, 3, 2, 2], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:06,  1.66it/s]

epoch:  8 loss:  0.14943534135818481
tensor([1, 4, 3, 4, 1, 0, 2, 4, 3, 3, 3, 4, 2, 1, 2, 3, 2, 3, 3, 4, 4, 2, 2, 2,
        1, 1, 3, 2, 3, 2, 4, 1], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.61it/s]

epoch:  8 loss:  0.04755623638629913
tensor([2, 1, 0, 1, 3, 3, 4, 2, 4, 2, 3, 1, 1, 4, 0, 3, 2, 1, 2, 0, 2, 1, 3, 0,
        4, 0, 2, 1, 1, 3, 2, 3], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.35it/s]

epoch:  8 loss:  0.05553646385669708
tensor([3, 4, 2, 4, 0, 3, 4, 3, 1, 2, 2, 1, 2, 2, 1, 3, 3, 2, 2, 2, 0, 4, 0, 2,
        2, 3, 2, 2, 1, 4, 1, 4], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.26it/s]

epoch:  8 loss:  0.058932214975357056
tensor([2, 1, 2, 3, 3, 3, 3, 1, 0, 3, 2, 2, 1, 1, 2, 4, 3, 0, 0, 1, 0, 3, 0, 0,
        4, 3, 3, 1, 3, 2, 3, 2], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.26it/s]

epoch:  8 loss:  0.06615244597196579
tensor([1, 1, 3, 4, 4, 3, 2, 3, 3, 2, 3, 2, 4, 2, 3, 4, 4, 4, 4, 0, 0, 4, 0, 0,
        1, 3, 1, 3, 4, 1, 0, 4], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.22it/s]

epoch:  8 loss:  0.07635928690433502
tensor([3, 2, 3, 3, 3, 3, 3, 4, 3, 2, 4, 2, 3, 1, 2, 2, 1, 0, 1, 3, 4, 0, 1, 4,
        1, 1, 4, 4, 2, 1, 4, 4], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.20it/s]

epoch:  8 loss:  0.04478579759597778
tensor([1, 4, 4, 4, 3, 1, 3, 2, 2, 4, 2, 4, 4, 2, 1, 1, 0, 4, 3, 4, 4, 2, 2, 0,
        1, 2, 4, 3, 4, 2, 4, 1], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.24it/s]

epoch:  8 loss:  0.04227084666490555
tensor([2, 2, 2, 3, 2, 4, 1, 2, 3, 4, 4, 0, 2, 2, 0, 0, 1, 0, 3, 2, 0, 1, 1, 2,
        3, 4, 4, 3, 3, 4, 2, 2], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.26it/s]

epoch:  8 loss:  0.05104471743106842
tensor([4, 2, 2, 0, 3, 3, 2, 2, 0, 1, 3, 2, 3, 3, 2, 4, 2, 3, 2, 0, 3, 3, 2, 2,
        4, 4, 1, 3, 2, 2, 1, 0], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.22it/s]

epoch:  8 loss:  0.04190244898200035
tensor([3, 2, 4, 4, 0, 1], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.34it/s]


epoch:  8 loss:  0.04652467742562294


100%|██████████| 5/5 [00:01<00:00,  3.66it/s]


              precision    recall  f1-score   support

           0       0.37      0.41      0.39        17
           1       0.32      0.43      0.37        23
           2       0.42      0.27      0.33        30
           3       0.41      0.57      0.48        40
           4       0.33      0.17      0.22        30

    accuracy                           0.38       140
   macro avg       0.37      0.37      0.36       140
weighted avg       0.38      0.38      0.36       140



  0%|          | 0/11 [00:00<?, ?it/s]

tensor([2, 1, 4, 4, 3, 2, 4, 2, 0, 0, 3, 1, 1, 3, 1, 3, 3, 0, 2, 4, 4, 0, 4, 2,
        1, 3, 1, 3, 0, 3, 2, 3], device='cuda:0')


  9%|▉         | 1/11 [00:00<00:05,  1.97it/s]

epoch:  9 loss:  0.025546442717313766
tensor([0, 1, 4, 1, 1, 2, 4, 3, 1, 3, 2, 3, 4, 1, 4, 3, 1, 2, 2, 1, 4, 2, 2, 1,
        3, 0, 4, 4, 3, 3, 1, 3], device='cuda:0')


 18%|█▊        | 2/11 [00:01<00:05,  1.54it/s]

epoch:  9 loss:  0.021316710859537125
tensor([2, 2, 2, 2, 1, 3, 0, 1, 3, 4, 0, 2, 0, 2, 4, 1, 1, 3, 1, 3, 3, 3, 4, 4,
        4, 4, 3, 2, 4, 2, 3, 3], device='cuda:0')


 27%|██▋       | 3/11 [00:02<00:05,  1.41it/s]

epoch:  9 loss:  0.019712476059794426
tensor([1, 0, 2, 3, 4, 4, 3, 4, 1, 0, 4, 1, 3, 2, 2, 0, 1, 1, 2, 3, 4, 4, 4, 2,
        4, 4, 1, 1, 1, 4, 3, 0], device='cuda:0')


 36%|███▋      | 4/11 [00:02<00:05,  1.29it/s]

epoch:  9 loss:  0.024605480954051018
tensor([0, 4, 2, 2, 0, 3, 3, 2, 1, 2, 1, 2, 4, 2, 2, 3, 2, 3, 3, 4, 3, 3, 1, 3,
        3, 1, 0, 2, 3, 4, 3, 3], device='cuda:0')


 45%|████▌     | 5/11 [00:03<00:04,  1.23it/s]

epoch:  9 loss:  0.03241148591041565
tensor([0, 1, 4, 0, 3, 3, 2, 2, 1, 4, 1, 2, 4, 1, 1, 2, 2, 4, 3, 2, 3, 2, 2, 3,
        2, 2, 2, 2, 4, 4, 2, 3], device='cuda:0')


 55%|█████▍    | 6/11 [00:04<00:04,  1.25it/s]

epoch:  9 loss:  0.023523271083831787
tensor([1, 0, 3, 0, 1, 2, 2, 0, 0, 4, 4, 2, 4, 3, 2, 4, 3, 4, 1, 1, 0, 4, 4, 3,
        2, 3, 2, 4, 3, 2, 0, 2], device='cuda:0')


 64%|██████▎   | 7/11 [00:05<00:03,  1.21it/s]

epoch:  9 loss:  0.03309473767876625
tensor([4, 4, 2, 0, 4, 1, 3, 2, 0, 1, 1, 3, 4, 2, 4, 2, 4, 4, 2, 1, 3, 3, 3, 2,
        2, 3, 3, 3, 2, 1, 3, 2], device='cuda:0')


 73%|███████▎  | 8/11 [00:06<00:02,  1.19it/s]

epoch:  9 loss:  0.022766059264540672
tensor([4, 2, 2, 3, 2, 3, 2, 4, 4, 0, 2, 0, 1, 4, 3, 3, 1, 2, 4, 2, 4, 0, 2, 2,
        4, 0, 0, 4, 4, 0, 3, 4], device='cuda:0')


 82%|████████▏ | 9/11 [00:07<00:01,  1.17it/s]

epoch:  9 loss:  0.025377992540597916
tensor([2, 2, 4, 2, 1, 2, 2, 2, 2, 3, 2, 3, 1, 3, 1, 3, 4, 4, 3, 3, 2, 1, 2, 1,
        2, 0, 2, 2, 3, 1, 4, 1], device='cuda:0')


 91%|█████████ | 10/11 [00:07<00:00,  1.21it/s]

epoch:  9 loss:  0.022963760420680046
tensor([3, 2, 4, 3, 2, 2], device='cuda:0')


100%|██████████| 11/11 [00:08<00:00,  1.32it/s]


epoch:  9 loss:  0.016316397115588188


100%|██████████| 5/5 [00:01<00:00,  3.89it/s]

              precision    recall  f1-score   support

           0       0.39      0.53      0.45        17
           1       0.42      0.43      0.43        23
           2       0.43      0.43      0.43        30
           3       0.42      0.33      0.37        40
           4       0.25      0.27      0.26        30

    accuracy                           0.38       140
   macro avg       0.38      0.40      0.39       140
weighted avg       0.38      0.38      0.38       140



In [14]:
# wandb.log({'epoch': epoch, 'f1': f1, 'acc': acc, 'precision': precision, 'recall': recall})
# torch.save(model.state_dict(), 'model/bert_cls_model.pth')

## 12. 分类报告

![bert_cls](../static/bert_cls.png)

可以看到精度较低，感觉是数据集太小了的缘故，而且分类又多，
这样每个类数据就更少了。
